(function(global){'use strict';var state=document.getElementById('account-state'),work=document.getElementById('account-work'),returnTo=global.FTN.Auth.returnPath();function esc(s){return String(s||'').replace(/[&<>"]/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c];});}function status(message,tone){var el=document.getElementById('account-status');if(el){el.textContent=message;el.dataset.tone=tone||'';}}
function guest(message){state.innerHTML='<p><strong>Guest</strong><br><small>No authenticated FTN session on this device.</small></p>';work.innerHTML='<div class="nexus-form"><h3>Continue with FTN</h3><p>Guest access remains open. Sign in only when you need protected identity, saved work or a private FTN task.</p><button class="btn btn-primary" type="button" id="account-google">Continue with Google</button><p class="nexus-status" id="account-status" role="status">'+esc(message||('After sign-in, FTN will return you to '+returnTo+'.'))+'</p><hr><h3>Use email instead</h3><p>FTN sends one secure sign-in link. Open that link in this same browser and tab profile; FTN will finish the sign-in automatically. New email addresses create an FTN Account.</p><form class="nexus-form" id="account-email-form"><label>Email address<input type="email" id="account-email" autocomplete="email" required></label><div data-turnstile-mount></div><button class="btn btn-outline" type="submit">Email my secure sign-in link</button></form></div>';
  document.getElementById('account-google').onclick=async function(){status('Opening secure Google sign-in…');try{var result=await global.FTN.Auth.signInWithGoogle(returnTo);if(result&&result.url)global.location.assign(result.url);else status('Google sign-in could not start. Please try again.','error');}catch(err){status(err.message||'Google sign-in could not start.','error');}};
  // Turnstile (2026-08-25): mounted fresh every time this form is (re)built, since
  // js/turnstile-gate.js's automatic DOMContentLoaded scan already ran before this markup existed
  // -- see that file's own mount() comment. Safe no-op if Turnstile isn't configured/reachable
  // (the widget shows its own "not active yet" fallback and the token stays empty) or if the
  // script hasn't loaded yet on this page (checked defensively; account.js does not add a hard
  // dependency on turnstile-gate.js being present).
  if(global.FTN.TurnstileGate&&typeof global.FTN.TurnstileGate.mount==='function')global.FTN.TurnstileGate.mount();
  document.getElementById('account-email-form').onsubmit=async function(e){e.preventDefault();var email=document.getElementById('account-email').value.trim();var tokenInput=document.querySelector('#account-email-form input[name="cf-turnstile-response"]');var captchaToken=tokenInput?tokenInput.value:undefined;status('Requesting a secure sign-in link…');try{await global.FTN.Auth.signInWithEmail(email,returnTo,captchaToken);try{sessionStorage.setItem('ftn.auth.email',email);}catch(x){}status('Email sent. Open its FTN sign-in link in this browser. If it opens in a different browser or private window, return here and request a fresh link.','success');}catch(err){status(err.message||'Sign-in email could not be sent.','error');}};
}
// Real browser-local FTN data classes, keyed by their actual current storage key (not an
// aspirational one nothing writes) -- fixed here after finding js/opportunities-workspace.js's
// real save key ('ftn-opportunities-saved-v3') didn't match what this file used to read
// ('ftn.opportunities.saved'), which silently made "My FTN" always report it as absent.
function localInventory(){var keys=['ftn-country','ftn-platform-mode','ftn-opportunities-saved-v3'],out={};keys.forEach(function(k){try{var v=localStorage.getItem(k);if(v!==null)out[k]=JSON.parse(v);}catch(e){}});return out;}
function download(data){var blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='ftn-account-export-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(function(){URL.revokeObjectURL(a.href);},1000);}
function authMethodLabel(user){var provider=(user.app_metadata&&user.app_metadata.provider)||'';if(provider==='google')return'Google';if(provider==='email')return'Email sign-in link';return provider?esc(provider):'Email sign-in link';}
function memberSince(user){var iso=user.created_at;if(!iso)return null;var d=new Date(iso);if(isNaN(d.getTime()))return null;return d.toLocaleDateString('en-US',{year:'numeric',month:'long',day:'numeric'});}
function savedItemsHtml(){var Save=global.FTN.Save,items=Save?Save.list():[],opp=(function(){try{var raw=localStorage.getItem('ftn-opportunities-saved-v3');var v=raw?JSON.parse(raw):[];return Array.isArray(v)?v.length:0;}catch(e){return 0;}})();
  var rows=items.map(function(i){return'<li><span>'+esc(i.title)+'</span>'+(i.url?'<a href="'+esc(i.url)+'" target="_blank" rel="noopener noreferrer">Open →</a>':'')+'</li>';}).join('');
  var oppLine=opp>0?'<p>'+opp+' saved '+(opp===1?'opportunity':'opportunities')+' — <a href="/opportunities/">open FTN Opportunities</a> to manage them.</p>':'';
  if(!items.length&&!opp)return'<p>Nothing saved yet. Use the ☆ Save control on FTN Live or FTN Opportunities to build your My FTN list here.</p>';
  return(items.length?'<ul class="nexus-list">'+rows+'</ul>':'')+oppLine;
}
async function signed(){var user=await global.FTN.Auth.getVerifiedUser();if(!user){guest();return;}
  var since=memberSince(user);
  state.innerHTML='<p><strong>Signed in</strong><br><small>'+esc(user.email||'FTN Account')+'</small></p><p><small>Signed in with</small><br>'+esc(authMethodLabel(user))+'</p>'+(since?'<p><small>Member since</small><br>'+esc(since)+'</p>':'')+'<p><small>Email confirmed</small><br>'+esc(user.email_confirmed_at?'Yes':'Not confirmed')+'</p><button class="btn btn-outline" id="account-signout" type="button">Sign out on this device</button>';
  // Identity -> My FTN -> Saved/Recent -> Founder/Membership -> Privacy/Permissions/Data, per
  // the FTN Account design hierarchy -- governance controls (preferences/deletion) stay lowest.
  work.innerHTML='<div class="nexus-account-state">'+
    '<section><h3>Return to your task</h3><p>Your requested return is <code>'+esc(returnTo)+'</code>.</p><a class="btn btn-primary" href="'+esc(returnTo)+'">Continue task</a></section><hr>'+
    '<section id="saved"><h3>My FTN — saved</h3><div id="account-saved-items">'+savedItemsHtml()+'</div></section><hr>'+
    '<section><h3>Local browser data</h3><p id="account-save-summary">Loading your browser-local FTN inventory…</p><div class="nexus-actions"><button type="button" id="account-export">Download my local FTN data</button></div></section>'+
    '<div id="account-founder-slot"></div>'+
    '<hr><section><h3>Consent and notifications</h3><form class="nexus-form" id="account-preferences"><label>Product updates<select name="product_updates"><option value="off">Off</option><option value="important">Important service notices only</option></select></label><button class="btn btn-outline" type="submit">Save preference</button></form><p class="nexus-status" id="account-status" role="status"></p></section><hr>'+
    '<section><h3>Deletion</h3><p>A deletion request is server recorded when the protected account-control function is available. Security/evidence exceptions remain governed by the retention notice.</p><label>Type DELETE to request deletion<input id="account-delete-confirm" autocomplete="off"></label><button class="btn btn-outline" id="account-delete" type="button">Request account deletion</button></section>'+
  '</div>';
  // Preserves the exact #account-owner-gate id + hidden-attribute contract
  // tests/founder-access-release.mjs verifies (present-but-hidden for non-founders, visible
  // with the God Mode link or approval form otherwise) -- only its position in the page moved,
  // per the My-FTN-before-Founder hierarchy.
  var founderPlaceholder=document.getElementById('account-founder-slot');
  var ownerGate=document.createElement('section');ownerGate.id='account-owner-gate';ownerGate.hidden=true;
  founderPlaceholder.replaceWith(ownerGate);
  var owner=await global.FTN.Auth.ownerAccess();
  if(owner&&owner.allowed){ownerGate.hidden=false;ownerGate.innerHTML='<span class="nexus-eyebrow">PRIVATE FOUNDER CONTROL</span><h3>FTN Nexus Command</h3><p>This Google identity and enrolled founder device were verified server-side.</p><a class="btn btn-primary" href="/god-mode/">Open God Mode</a><hr>';}
  else if(owner&&owner.ownerIdentity&&owner.deviceApprovalRequired){ownerGate.hidden=false;ownerGate.innerHTML='<span class="nexus-eyebrow">PRIVATE FOUNDER CONTROL</span><h3>Founder device approval required</h3><p>'+esc(owner.firstDevice?'Enroll this first founder device to open FTN Nexus Command.':'This signed-in Google identity is approved, but this device must be approved from an enrolled founder device before God Mode is exposed.')+'</p><form class="nexus-form" id="founder-device-form"><label>Device name<input id="founder-device-name" maxlength="120" required value="'+esc((navigator.platform||'Founder device')+' · '+new Date().toLocaleDateString())+'"></label><button class="btn btn-primary" type="submit">'+(owner.firstDevice?'Enroll this device':'Request device approval')+'</button><button class="btn btn-outline" id="founder-device-claim" type="button">Check approval and continue</button><p class="nexus-status" id="founder-device-status" role="status">No owner console data is available until device approval completes.</p></form><hr>';
    var founderStatus=document.getElementById('founder-device-status');document.getElementById('founder-device-form').onsubmit=async function(e){e.preventDefault();founderStatus.textContent='Recording this founder device securely…';var result=await global.FTN.Auth.enrollOwnerDevice(document.getElementById('founder-device-name').value);if(result.allowed){location.assign('/god-mode/');return;}founderStatus.textContent=result.error||'Approval requested. Approve this device from an enrolled founder device, then check again.';};
    document.getElementById('founder-device-claim').onclick=async function(){founderStatus.textContent='Checking founder device approval…';var result=await global.FTN.Auth.claimOwnerDevice();if(result.allowed){location.assign('/god-mode/');return;}founderStatus.textContent=result.error||'Approval is still required.';};
  }
  document.getElementById('account-save-summary').textContent=Object.keys(localInventory()).length+' approved local data classes are present on this browser. They are not evidence of cloud backup.';
  document.getElementById('account-signout').onclick=async function(){await global.FTN.Auth.signOut();guest('Signed out on this device.');};
  document.getElementById('account-export').onclick=function(){download({schema:'ftn-account-export-v1',exportedAt:new Date().toISOString(),user:{email:user.email},savedItems:global.FTN.Save?global.FTN.Save.list():[],localBrowserData:localInventory()});};
  document.getElementById('account-preferences').onsubmit=async function(e){e.preventDefault();var value=e.target.product_updates.value;try{var c=await global.FTN.Auth.ready(),r=await c.from('ftn_user_preferences').upsert({user_id:user.id,product_updates:value,updated_at:new Date().toISOString()},{onConflict:'user_id'});if(r.error)throw r.error;status('Preference saved to your FTN Account.','success');}catch(err){status('Cloud preference storage is not available in this release environment. No success was recorded.','error');}};
  document.getElementById('account-delete').onclick=async function(){if(document.getElementById('account-delete-confirm').value!=='DELETE'){status('Type DELETE exactly before requesting deletion.','error');return;}status('Recording deletion request…');try{await global.FTN.Auth.invoke('ftn-account-control',{action:'request-deletion'});status('Deletion request recorded. You will be signed out.','success');setTimeout(async function(){await global.FTN.Auth.signOut();guest('Deletion request recorded; signed out.');},1200);}catch(err){status('Deletion request service is unavailable. No deletion was claimed. Contact FTN Privacy with your account ID if this persists.','error');}};
}
async function boot(){try{var callbackError=global.FTN.Auth.consumeAuthCallbackError&&global.FTN.Auth.consumeAuthCallbackError();if(callbackError){if(callbackError.kind==='cancelled')guest('Google sign-in was cancelled. No FTN session was created.');else if(callbackError.kind==='provider_config')guest('Google sign-in is temporarily unavailable because the secure provider connection could not be verified. Use email sign-in for a standard FTN Account; God Mode remains closed until Google sign-in is restored.');else guest('FTN could not complete this sign-in. No session was created. Try again or use email sign-in.');return;}await global.FTN.Auth.completeAuthRedirect();var user=await global.FTN.Auth.getVerifiedUser();if(user)await signed();else guest();}catch(error){guest('This sign-in link could not be completed. Request a fresh link and open it in this same browser.');}}
boot();global.FTN.Auth.onChange(function(event,session){if(session&&event==='SIGNED_IN')signed();});})(window);
