(function(global){'use strict';var state=document.getElementById('account-state'),work=document.getElementById('account-work'),returnTo=global.FTN.Auth.returnPath();function esc(s){return String(s||'').replace(/[&<>"]/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c];});}function status(message,tone){var el=document.getElementById('account-status');if(el){el.textContent=message;el.dataset.tone=tone||'';}}
function guest(message){state.innerHTML='<p><strong>Guest</strong><br><small>No authenticated FTN session on this device.</small></p>';work.innerHTML='<div class="nexus-form"><h3>Continue by email</h3><p>FTN will send a short-lived magic link or one-time code, depending on the configured email template. New email addresses create an FTN Account.</p><form class="nexus-form" id="account-email-form"><label>Email address<input type="email" id="account-email" autocomplete="email" required></label><button class="btn btn-primary" type="submit">Email my secure sign-in</button></form><form class="nexus-form" id="account-otp-form"><label>One-time code (if your email contains one)<input id="account-otp" inputmode="numeric" autocomplete="one-time-code" pattern="[0-9]{6,8}"></label><button class="btn btn-outline" type="submit">Verify code</button></form><p class="nexus-status" id="account-status" role="status">'+esc(message||('After sign-in, FTN will return you to '+returnTo+'.'))+'</p></div>';
  document.getElementById('account-email-form').onsubmit=async function(e){e.preventDefault();var email=document.getElementById('account-email').value.trim();status('Requesting a secure sign-in email…');try{await global.FTN.Auth.signInWithEmail(email,returnTo);try{sessionStorage.setItem('ftn.auth.email',email);}catch(x){}status('Email sent. Use its secure link, or enter the one-time code shown in the message.','success');}catch(err){status(err.message||'Sign-in email could not be sent.','error');}};
  document.getElementById('account-otp-form').onsubmit=async function(e){e.preventDefault();var email=document.getElementById('account-email').value.trim()||sessionStorage.getItem('ftn.auth.email')||'',token=document.getElementById('account-otp').value.trim();if(!email||!token){status('Enter the email address and the code from that email.','error');return;}status('Verifying…');try{await global.FTN.Auth.verifyEmailOtp(email,token);await signed();}catch(err){status(err.message||'That code could not be verified.','error');}};
}
function localInventory(){var keys=['ftn.last-public-task','ftn.parliament.saved','ftn.invest.watchlist','ftn.opportunities.saved','ftn.saved-pages','ftn.country','ftn.platform.mode'],out={};keys.forEach(function(k){try{var v=localStorage.getItem(k);if(v!==null)out[k]=JSON.parse(v);}catch(e){}});return out;}
function download(data){var blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='ftn-account-export-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(function(){URL.revokeObjectURL(a.href);},1000);}
async function signed(){var user=await global.FTN.Auth.getVerifiedUser();if(!user){guest();return;}state.innerHTML='<p><strong>Signed in</strong><br><small>'+esc(user.email||user.id)+'</small></p><p><small>User ID</small><br><code>'+esc(user.id)+'</code></p><p><small>Email confirmed</small><br>'+esc(user.email_confirmed_at?'Yes':'Not confirmed')+'</p><button class="btn btn-outline" id="account-signout" type="button">Sign out on this device</button>';work.innerHTML='<div class="nexus-account-state"><section><h3>Return to your task</h3><p>Your requested return is <code>'+esc(returnTo)+'</code>.</p><a class="btn btn-primary" href="'+esc(returnTo)+'">Continue task</a></section><hr><section><h3>Saved work and portable export</h3><p id="account-save-summary">Loading your browser-local FTN inventory…</p><div class="nexus-actions"><button type="button" id="account-export">Download my local FTN data</button></div></section><hr><section><h3>Consent and notifications</h3><form class="nexus-form" id="account-preferences"><label>Product updates<select name="product_updates"><option value="off">Off</option><option value="important">Important service notices only</option></select></label><button class="btn btn-outline" type="submit">Save preference</button></form><p class="nexus-status" id="account-status" role="status"></p></section><hr><section><h3>Deletion</h3><p>A deletion request is server recorded when the protected account-control function is available. Security/evidence exceptions remain governed by the retention notice.</p><label>Type DELETE to request deletion<input id="account-delete-confirm" autocomplete="off"></label><button class="btn btn-outline" id="account-delete" type="button">Request account deletion</button></section></div>';
  document.getElementById('account-save-summary').textContent=Object.keys(localInventory()).length+' approved local data classes are present on this browser. They are not evidence of cloud backup.';
  document.getElementById('account-signout').onclick=async function(){await global.FTN.Auth.signOut();guest('Signed out on this device.');};document.getElementById('account-export').onclick=function(){download({schema:'ftn-account-export-v1',exportedAt:new Date().toISOString(),user:{id:user.id,email:user.email},localBrowserData:localInventory()});};
  document.getElementById('account-preferences').onsubmit=async function(e){e.preventDefault();var value=e.target.product_updates.value;try{var c=await global.FTN.Auth.ready(),r=await c.from('ftn_user_preferences').upsert({user_id:user.id,product_updates:value,updated_at:new Date().toISOString()},{onConflict:'user_id'});if(r.error)throw r.error;status('Preference saved to your FTN Account.','success');}catch(err){status('Cloud preference storage is not available in this release environment. No success was recorded.','error');}};
  document.getElementById('account-delete').onclick=async function(){if(document.getElementById('account-delete-confirm').value!=='DELETE'){status('Type DELETE exactly before requesting deletion.','error');return;}status('Recording deletion request…');try{await global.FTN.Auth.invoke('ftn-account-control',{action:'request-deletion'});status('Deletion request recorded. You will be signed out.','success');setTimeout(async function(){await global.FTN.Auth.signOut();guest('Deletion request recorded; signed out.');},1200);}catch(err){status('Deletion request service is unavailable. No deletion was claimed. Contact FTN Privacy with your account ID if this persists.','error');}};
}
global.FTN.Auth.getVerifiedUser().then(function(user){if(user)signed().catch(function(e){guest(e.message);});else guest();}).catch(function(){guest('FTN Account could not reach the authentication service. Check your connection and try again.');});global.FTN.Auth.onChange(function(event,session){if(session&&event==='SIGNED_IN')signed();});})(window);
