(() => {
'use strict';
const videos=[{id:'JZ4h_ldPUgk',title:'Soca 2026 Mix — Soca Spark 26',creator:'DJ Ana & Ultra Simmo',genre:'Soca',region:'Trinidad & Tobago',duration:'Mix',source:'YouTube',featured:true},{id:'svCJ3C5LviI',title:'Trinidad Carnival 2026 Road Power Soca DJ Mix',creator:'Sir Trey Benjamin',genre:'Soca',region:'Trinidad & Tobago',duration:'Mix',source:'YouTube',featured:true},{id:'VG-NhYHjPrE',title:'Dancehall Mix 2026 — 50 Best Dancehall Songs',creator:'DJ Treasure',genre:'Dancehall',region:'Jamaica',duration:'Mix',source:'YouTube',featured:false},{id:'eKIOU9X0MxI',title:'Dancehall Mix 2026 Vol. 4 — Raw & Clean',creator:'ZJ Liquid Music',genre:'Dancehall',region:'Jamaica',duration:'Mix',source:'YouTube',featured:false}];
const categories=[['Soca','Power, groovy, jab & road'],['Dancehall','Jamaica & the wider Caribbean'],['Reggae','Roots, lovers & modern reggae'],['Bouyon','Fast, raw Caribbean energy'],['Live Sessions','Sets, stages & behind the decks']];
const featureGrid=document.querySelector('#dj-feature-grid'),videoGrid=document.querySelector('#dj-video-grid'),categoryGrid=document.querySelector('#dj-category-grid'),searchInput=document.querySelector('#dj-search-input'),emptyState=document.querySelector('#dj-empty');
const thumb=id=>`https://i.ytimg.com/vi/${encodeURIComponent(id)}/hqdefault.jpg`;
const esc=v=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function openPlayer(video){const modal=document.createElement('div');modal.className='dj-modal';modal.setAttribute('role','dialog');modal.setAttribute('aria-modal','true');modal.setAttribute('aria-label',video.title);modal.innerHTML=`<div class="dj-modal__dialog"><div class="dj-modal__video"><iframe src="https://www.youtube.com/embed/${encodeURIComponent(video.id)}?autoplay=1&rel=0" title="${esc(video.title)}" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></div><div class="dj-modal__bar"><div><h2>${esc(video.title)}</h2><small>${esc(video.creator)} · ${esc(video.region)}</small></div><button class="dj-modal__close" type="button" aria-label="Close video">&times;</button></div></div>`;document.body.appendChild(modal);document.body.classList.add('is-modal-open');const close=()=>{modal.remove();document.body.classList.remove('is-modal-open')};modal.querySelector('.dj-modal__close').addEventListener('click',close);modal.addEventListener('click',e=>{if(e.target===modal)close()});document.addEventListener('keydown',function onKey(e){if(e.key==='Escape'){close();document.removeEventListener('keydown',onKey)}})}
function cardAttrs(v){return `data-dj-queue-add data-video-id="${esc(v.id)}" data-title="${esc(v.title)}" data-creator="${esc(v.creator)}" data-genre="${esc(v.genre)}" data-region="${esc(v.region)}"`}
function renderFeatured(){if(!featureGrid)return;const featured=videos.filter(v=>v.featured),primary=featured[0],secondary=featured.slice(1,3);featureGrid.innerHTML=`<article class="dj-feature-card" ${cardAttrs(primary)}><div class="dj-feature-card__media" style="background-image:url('${thumb(primary.id)}')"></div><div class="dj-feature-card__overlay"></div><div class="dj-feature-card__content"><span class="dj-pill">Featured</span><h3>${esc(primary.title)}</h3><div class="dj-meta">${esc(primary.creator)} · ${esc(primary.region)}</div><button type="button" class="btn btn-primary dj-add-player">Add to DJ Player</button></div></article><div class="dj-feature-stack">${secondary.map(v=>`<article class="dj-feature-card dj-feature-card--small" ${cardAttrs(v)}><div class="dj-feature-card__media" style="background-image:url('${thumb(v.id)}')"></div><div class="dj-feature-card__overlay"></div><div class="dj-feature-card__content"><span class="dj-pill">${esc(v.genre)}</span><h3>${esc(v.title)}</h3><div class="dj-meta">${esc(v.creator)}</div><button type="button" class="btn btn-secondary dj-add-player">Add to DJ Player</button></div></article>`).join('')}</div>`}
function renderCategories(){if(!categoryGrid)return;categoryGrid.innerHTML=categories.map(([n,d])=>`<a class="dj-category" href="#latest-heading" data-category-link="${esc(n)}"><strong>${esc(n)}</strong><span>${esc(d)}</span></a>`).join('');categoryGrid.querySelectorAll('[data-category-link]').forEach(link=>link.addEventListener('click',e=>{e.preventDefault();const f=document.querySelector(`[data-filter="${CSS.escape(link.dataset.categoryLink)}"]`);if(f)f.click();document.querySelector('#latest-heading')?.scrollIntoView({behavior:'smooth',block:'start'})}))}
function renderVideos(filter='all',query=''){if(!videoGrid)return;const q=query.trim().toLowerCase(),results=videos.filter(v=>(filter==='all'||v.genre===filter||v.region===filter)&&(!q||`${v.title} ${v.creator} ${v.genre} ${v.region}`.toLowerCase().includes(q)));videoGrid.innerHTML=results.map(v=>`<article class="dj-video-card" ${cardAttrs(v)} tabindex="0" role="button" aria-label="Add ${esc(v.title)} to DJ Player"><div class="dj-video-thumb" style="background-image:url('${thumb(v.id)}')"><span class="dj-play" aria-hidden="true">▶</span></div><div class="dj-video-body"><div class="dj-meta"><span>${esc(v.genre)}</span><span>·</span><span>${esc(v.region)}</span></div><h3>${esc(v.title)}</h3><p>${esc(v.creator)} · ${esc(v.source)}</p><button type="button" class="btn btn-secondary dj-add-player">Add to DJ Player</button></div></article>`).join('');emptyState.hidden=results.length!==0;videoGrid.querySelectorAll('[data-dj-queue-add]').forEach(card=>{card.addEventListener('click',e=>{if(e.target.closest('.dj-add-player'))return;const v=videos.find(x=>x.id===card.dataset.videoId);if(v)openPlayer(v)});card.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&!e.target.closest('button')){e.preventDefault();const v=videos.find(x=>x.id===card.dataset.videoId);if(v)openPlayer(v)}})})}
let activeFilter='all';document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{activeFilter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('is-active',x===b));renderVideos(activeFilter,searchInput?.value||'')}));searchInput?.addEventListener('input',()=>renderVideos(activeFilter,searchInput.value));renderFeatured();renderCategories();renderVideos();
})();
