(function(global){
'use strict';
var root=document.getElementById('god-mode-root'),STATUS=['LIVE','AVAILABLE','PRIVATE','PHASE 2','ILLUSTRATIVE','TEMPORARILY UNAVAILABLE'];
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function date(s){if(!s)return'Never';try{return new Date(s).toLocaleString();}catch(e){return String(s);}}
function deny(message){root.innerHTML='<span class="nexus-eyebrow">FTN NEXUS COMMAND · PRIVATE</span><h1>Authorization required.</h1><p>'+esc(message||'Private authorization denied.')+'</p><div class="nexus-actions"><a class="nexus-primary" href="/account/?return=%2Fgod-mode%2F">Open FTN Account</a><a href="/">Return to FTN Platform</a></div><p class="nexus-status">No owner data has been returned to this browser.</p>';}
function approval(data){root.innerHTML='<span class="nexus-eyebrow">FTN NEXUS COMMAND · PRIVATE</span><h1>Founder device approval required</h1><p>'+esc(data.firstDevice?'This approved Google identity may enroll the first founder device.':'Approve this device from an already enrolled founder device. God Mode remains closed until approval is claimed.')+'</p><form class="nexus-form" id="god-device-form"><label>Device name<input id="god-device-name" maxlength="120" required value="'+esc((navigator.platform||'Founder device')+' · '+new Date().toLocaleDateString())+'"></label><div class="nexus-actions"><button class="nexus-primary" type="submit">'+(data.firstDevice?'Enroll this device':'Request approval')+'</button><button type="button" id="god-device-claim">Check approval</button><a href="/account/">Account</a></div><p class="nexus-status" id="god-device-status" role="status">No private console data is available.</p></form>';var status=document.getElementById('god-device-status');document.getElementById('god-device-form').onsubmit=async function(e){e.preventDefault();status.textContent='Recording the device request…';var result=await global.FTN.Auth.enrollOwnerDevice(document.getElementById('god-device-name').value);if(result.allowed){location.reload();return;}status.textContent=result.error||'Approval requested.';};document.getElementById('god-device-claim').onclick=async function(){status.textContent='Checking approval…';var result=await global.FTN.Auth.claimOwnerDevice();if(result.allowed){location.reload();return;}status.textContent=result.error||'Approval is still required.';};}
function statusOptions(current){return STATUS.map(function(x){return'<option'+(x===current?' selected':'')+'>'+x+'</option>';}).join('');}
function table(rows,columns,empty){if(!rows.length)return'<p class="nexus-status">'+esc(empty)+'</p>';return'<div style="overflow:auto"><table class="nexus-table"><thead><tr>'+columns.map(function(c){return'<th>'+esc(c[0])+'</th>';}).join('')+'</tr></thead><tbody>'+rows.map(function(row){return'<tr>'+columns.map(function(c){return'<td>'+esc(typeof c[1]==='function'?c[1](row):row[c[1]])+'</td>';}).join('')+'</tr>';}).join('')+'</tbody></table></div>';}
async function mutate(body,message){var out=document.getElementById('god-action-status');out.textContent='Saving a journalled owner action…';try{var result=await global.FTN.Auth.ownerInvoke(body);if(result.error)throw new Error(result.error);out.textContent=message+' Journal '+(result.journalId||'recorded')+'.';setTimeout(load,500);}catch(error){out.textContent='No change was claimed: '+(error.message||'owner action failed');}}
function control(action){var word=action==='nuclear'?'NUCLEAR':action.toUpperCase(),entered=prompt('Type '+word+' to confirm this staged owner-control simulation.');if(entered!==word)return;var reason=prompt('State the operational reason.');if(reason)mutate({action:'emergency',mode:action,reason:reason,dryRun:true},'Simulation recorded');}
function render(data){
  var registry=global.FTN.ProductRegistry.all(),savedById={};(data.products||[]).forEach(function(x){savedById[x.product_id]=x;});
  var productRows=registry.map(function(p){var saved=savedById[p.id]||{};return{id:p.id,name:saved.name||p.name,status:saved.status||p.status,route:saved.route||p.route,parent:saved.parent_product||p.parentProduct||'',visible:saved.public_visibility==null?p.publicVisibility:saved.public_visibility};});
  var devices=data.devices||[],sources=data.sources||[],health={};(data.linkHealth||[]).forEach(function(x){health[x.source_id]=x;});
  root.innerHTML='<span class="nexus-eyebrow">FTN NEXUS COMMAND · VERIFIED FOUNDER DEVICE</span><h1>God Mode</h1><p>Google identity, active Supabase session and revocable device credential were verified server-side. No provider secret or credential is present in this console.</p><p class="nexus-status" id="god-action-status" role="status">Current platform state: '+esc((data.state&&data.state.mode)||'normal')+'.</p>'+
  '<div class="nexus-grid nexus-grid--2"><article class="nexus-card nexus-card--dark"><h2>System safety</h2><p>These controls are staged, journalled and non-destructive by default.</p><div class="nexus-actions"><button type="button" data-emergency="pause">Pause</button><button type="button" data-emergency="lockdown">Lockdown</button><button type="button" data-emergency="nuclear">Nuclear</button></div></article><article class="nexus-card nexus-card--dark"><h2>Deployment and health</h2><p>'+(data.deployments||[]).length+' recorded deployment checks · '+(data.readiness||[]).length+' integration readiness records · '+sources.length+' controlled sources.</p><div class="nexus-actions"><a href="/">Open public FTN</a><button type="button" id="god-refresh">Refresh private state</button></div></article></div>'+
  '<section class="nexus-section"><h2>Founder devices</h2><p>Approve a pending device, or revoke a lost or old device. The current credential stops working immediately after revocation.</p><div class="nexus-grid">'+devices.map(function(d){return'<article class="nexus-card nexus-card--dark"><div class="nexus-meta"><span>'+esc(d.status)+'</span></div><h3>'+esc(d.device_name)+'</h3><p>Created '+esc(date(d.created_at))+'<br>Last used '+esc(date(d.last_used_at))+'<br>Revoked '+esc(date(d.revoked_at))+'</p><div class="nexus-actions">'+(d.status==='PENDING'?'<button type="button" data-approve-device="'+esc(d.id)+'">Approve</button>':'')+(d.status!=='REVOKED'?'<button type="button" data-revoke-device="'+esc(d.id)+'">Revoke</button>':'')+'</div></article>';}).join('')+'</div></section>'+
  '<section class="nexus-section"><h2>Product Registry controls</h2><p>Names, hierarchy, routes, release state and public visibility remain one journalled control record per registry product.</p><div class="nexus-grid">'+productRows.map(function(p){return'<form class="nexus-card nexus-card--dark" data-product-form="'+esc(p.id)+'"><label>Official name<input name="name" value="'+esc(p.name)+'" required></label><label>Parent product<input name="parentProduct" value="'+esc(p.parent)+'"></label><label>Route<input name="route" value="'+esc(p.route)+'" required></label><label>Status<select name="status">'+statusOptions(p.status)+'</select></label><label><input type="checkbox" name="publicVisibility"'+(p.visible?' checked':'')+'> Public visibility</label><label>Reason<input name="reason" value="Registry alignment for production release" required minlength="8"></label><button type="submit">Save '+esc(p.name)+'</button></form>';}).join('')+'</div></section>'+
  '<section class="nexus-section"><h2>Feature visibility</h2><p>Feature flags are independent from product status and default private.</p><form class="nexus-card nexus-card--dark" id="feature-form"><label>Feature key<input name="featureKey" required placeholder="parliament.live-lane"></label><label>Product ID<input name="productId" required></label><label>Visibility<select name="visibility"><option>PRIVATE</option><option>AUTHENTICATED</option><option>PUBLIC</option></select></label><label><input type="checkbox" name="enabled"> Enabled</label><label>Expiry<input name="expiresAt" type="datetime-local"></label><label>Reason<input name="reason" required minlength="8"></label><button type="submit">Save feature control</button></form>'+table(data.features||[],[['Feature','feature_key'],['Product','product_id'],['Visibility','visibility'],['Enabled',function(x){return x.enabled?'Yes':'No';}],['Expires',function(x){return date(x.expires_at);}]],'No feature overrides are recorded.')+'</section>'+
  '<section class="nexus-section"><h2>Source catalogue and link health</h2><p>FTN Live, FTN Parliament, FTN TV and FTN Kaiso source records carry ownership, confidence, availability and verification state.</p><form class="nexus-card nexus-card--dark" id="source-form"><label>Source ID<input name="sourceId" required></label><label>Product<select name="productId"><option value="ftn-live">FTN Live</option><option value="parliament">FTN Parliament</option><option value="tv">FTN TV</option><option value="kaiso">FTN Kaiso</option></select></label><label>Name<input name="name" required></label><label>Official HTTPS URL<input name="officialUrl" type="url" required></label><label>Confidence<select name="confidence"><option>VERIFIED OFFICIAL</option><option>HIGH</option><option>MEDIUM</option><option>LOW</option><option>UNVERIFIED</option></select></label><label>State<select name="availabilityState"><option>LIVE</option><option>PUBLISHED</option><option>ARCHIVE</option><option>OFFLINE</option><option>TEMPORARILY UNAVAILABLE</option></select></label><label>Last verified<input name="lastVerified" type="date"></label><label>Reason<input name="reason" required minlength="8"></label><button type="submit">Save source</button></form><div class="nexus-grid">'+sources.map(function(s){var h=health[s.source_id]||{};return'<article class="nexus-card nexus-card--dark"><div class="nexus-meta"><span>'+esc(s.product_id)+'</span><span>'+esc(s.confidence)+'</span><span>'+esc(s.availability_state)+'</span></div><h3>'+esc(s.name)+'</h3><p>'+esc(s.official_url)+'<br>Verified '+esc(s.last_verified||'not recorded')+' · Health '+esc(h.health_state||'UNCHECKED')+'</p><button type="button" data-check-source="'+esc(s.source_id)+'">Check link health</button></article>';}).join('')+'</div></section>'+
  '<section class="nexus-section"><h2>User access grants</h2><form class="nexus-card nexus-card--dark" id="grant-form"><label>Supabase user ID<input name="userId" required></label><label>Grant key<input name="grantKey" required></label><label>Expiry<input name="expiresAt" type="datetime-local"></label><label>Reason<input name="reason" required minlength="8"></label><button type="submit">Grant or renew access</button></form>'+table(data.accessGrants||[],[['User','user_id'],['Grant','grant_key'],['Expires',function(x){return date(x.expires_at);}],['Revoked',function(x){return date(x.revoked_at);}]],'No user grants are recorded.')+'</section>'+
  '<section class="nexus-section"><h2>Content and integration readiness</h2><form class="nexus-card nexus-card--dark" id="integration-form"><label>Integration ID<input name="integrationId" required></label><label>Product ID<input name="productId" required></label><label>Readiness<select name="readiness"><option>NOT READY</option><option>LIMITED</option><option>READY</option><option>OWNER ACTION</option></select></label><label>Public summary<input name="publicSummary" required></label><label>Private note<textarea name="privateNote"></textarea></label><label>Reason<input name="reason" required minlength="8"></label><button type="submit">Save readiness</button></form>'+table(data.readiness||[],[['Integration','integration_id'],['Product','product_id'],['Readiness','readiness'],['Verified',function(x){return date(x.last_verified);}]],'No integration readiness records are present.')+'</section>'+
  '<section class="nexus-section"><h2>Founder action register</h2><p>Owner-only account setup, affiliate review, provider verification and outreach tasks. No external account or message is created from this register.</p><div class="nexus-grid">'+(data.founderActions||[]).map(function(a){return'<form class="nexus-card nexus-card--dark" data-founder-action="'+esc(a.action_id)+'"><div class="nexus-meta"><span>'+esc(a.area)+'</span><span>'+esc(a.status)+'</span><span>'+(a.requires_owner_approval?'OWNER APPROVAL':'OPERATIONAL')+'</span></div><h3>'+esc(a.title)+'</h3><p>'+esc(a.owner_action)+'</p>'+(a.official_url?'<p><a href="'+esc(a.official_url)+'" target="_blank" rel="noopener noreferrer">Open official provider ↗</a></p>':'')+'<label>Status<select name="status"><option'+(a.status==='PENDING'?' selected':'')+'>PENDING</option><option'+(a.status==='APPROVED'?' selected':'')+'>APPROVED</option><option'+(a.status==='COMPLETE'?' selected':'')+'>COMPLETE</option><option'+(a.status==='DEFERRED'?' selected':'')+'>DEFERRED</option></select></label><label>Private note<textarea name="notes">'+esc(a.notes||'')+'</textarea></label><label>Reason<input name="reason" required minlength="8" value="Founder reviewed this owner-only action"></label><button type="submit">Update action</button></form>';}).join('')+'</div></section>'+
  '<section class="nexus-section"><h2>Deployment records</h2>'+table(data.deployments||[],[['Environment','environment'],['Commit','commit_sha'],['Deploy','deployment_state'],['Functional','functional_state'],['Checked',function(x){return date(x.checked_at);}]],'No deployment health record is present yet.')+'</section>'+
  '<section class="nexus-section"><h2>Audit records</h2><h3>Access attempts</h3>'+table(data.audit||[],[['Outcome','outcome'],['Reason','reason_code'],['Action','action'],['Device','device_id'],['When',function(x){return date(x.created_at);}]],'No owner access attempts are recorded.')+'<h3>Control changes</h3>'+table(data.journal||[],[['Action','action'],['Target','target'],['Reason','reason'],['Device','device_id'],['When',function(x){return date(x.created_at);}]],'No owner control changes are recorded.')+'</section>';
  document.querySelectorAll('[data-emergency]').forEach(function(b){b.onclick=function(){control(b.dataset.emergency);};});document.getElementById('god-refresh').onclick=load;
  document.querySelectorAll('[data-product-form]').forEach(function(form){form.onsubmit=function(e){e.preventDefault();var fd=new FormData(form);mutate({action:'product-control',productId:form.dataset.productForm,name:fd.get('name'),parentProduct:fd.get('parentProduct'),route:fd.get('route'),status:fd.get('status'),publicVisibility:fd.get('publicVisibility')==='on',reason:fd.get('reason')},'Product control saved');};});
  document.getElementById('feature-form').onsubmit=function(e){e.preventDefault();var fd=new FormData(e.target);mutate({action:'feature-control',featureKey:fd.get('featureKey'),productId:fd.get('productId'),visibility:fd.get('visibility'),enabled:fd.get('enabled')==='on',expiresAt:fd.get('expiresAt')||null,reason:fd.get('reason')},'Feature control saved');};
  document.getElementById('source-form').onsubmit=function(e){e.preventDefault();var fd=new FormData(e.target);mutate({action:'source-control',sourceId:fd.get('sourceId'),productId:fd.get('productId'),name:fd.get('name'),officialUrl:fd.get('officialUrl'),confidence:fd.get('confidence'),availabilityState:fd.get('availabilityState'),lastVerified:fd.get('lastVerified')||null,reason:fd.get('reason')},'Source control saved');};
  document.getElementById('grant-form').onsubmit=function(e){e.preventDefault();var fd=new FormData(e.target);mutate({action:'access-grant',userId:fd.get('userId'),grantKey:fd.get('grantKey'),expiresAt:fd.get('expiresAt')||null,reason:fd.get('reason')},'Access grant saved');};
  document.getElementById('integration-form').onsubmit=function(e){e.preventDefault();var fd=new FormData(e.target);mutate({action:'integration-control',integrationId:fd.get('integrationId'),productId:fd.get('productId'),readiness:fd.get('readiness'),publicSummary:fd.get('publicSummary'),privateNote:fd.get('privateNote'),reason:fd.get('reason')},'Integration readiness saved');};
  document.querySelectorAll('[data-founder-action]').forEach(function(form){form.onsubmit=function(e){e.preventDefault();var fd=new FormData(form);mutate({action:'founder-action',actionId:form.dataset.founderAction,status:fd.get('status'),notes:fd.get('notes'),reason:fd.get('reason')},'Founder action updated');};});
  document.querySelectorAll('[data-approve-device]').forEach(function(b){b.onclick=function(){mutate({action:'approve-device',deviceId:b.dataset.approveDevice,reason:'Approved from an enrolled founder device'},'Device approved for secure claim');};});
  document.querySelectorAll('[data-revoke-device]').forEach(function(b){b.onclick=function(){var reason=prompt('State why this founder device is being revoked.');if(reason)mutate({action:'revoke-device',deviceId:b.dataset.revokeDevice,reason:reason},'Device revoked');};});
  document.querySelectorAll('[data-check-source]').forEach(function(b){b.onclick=function(){mutate({action:'check-link',sourceId:b.dataset.checkSource},'Link health checked');};});
}
async function load(){try{var access=await global.FTN.Auth.ownerAccess();if(!access||!access.allowed){if(access&&access.ownerIdentity&&access.deviceApprovalRequired)approval(access);else deny((access&&access.error)||'Private authorization denied.');return;}var data=await global.FTN.Auth.ownerInvoke({action:'dashboard'});render(data);}catch(error){deny(error.message||'Owner control is unavailable or authorization was denied.');}}
load();
})(window);
