(function(global){
'use strict';
var URL='https://jshmidfpqrajxtukzges.supabase.co',KEY='sb_publishable_-1v6ZXAU3sXc7Z0L2VnFgw_638Qxu3z';
var root=document.getElementById('god-mode-root'),busy=false;
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
async function session(){try{return global.FTN&&global.FTN.Auth?await global.FTN.Auth.getSession():null;}catch(e){return null;}}
async function rpc(name,payload){var s=await session();if(!s)throw new Error('No owner session');var r=await fetch(URL+'/rest/v1/rpc/'+name,{method:'POST',headers:{apikey:KEY,Authorization:'Bearer '+s.access_token,'Content-Type':'application/json'},body:JSON.stringify(payload||{})});if(!r.ok)throw new Error('Institutional memory request denied');return await r.json();}
function style(){if(document.getElementById('nexus-memory-style'))return;var s=document.createElement('style');s.id='nexus-memory-style';s.textContent='.nexus-memory-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px}.nexus-memory-card{border:1px solid rgba(255,255,255,.14);border-radius:10px;padding:10px}.nexus-memory-card strong{display:block;font-size:1.35rem}.nexus-memory-list{display:grid;gap:8px;margin-top:12px}.nexus-memory-row{border-top:1px solid rgba(255,255,255,.12);padding-top:9px}.nexus-memory-row h3{font-size:.9rem;margin:0 0 4px}.nexus-memory-row p{font-size:.78rem;margin:.2rem 0;line-height:1.4}.nexus-memory-form{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px;margin-top:12px}.nexus-memory-form label{display:grid;gap:4px;font-size:.72rem}.nexus-memory-form input,.nexus-memory-form select,.nexus-memory-form textarea{min-height:38px;border-radius:8px;padding:7px;background:#111;color:#fff;border:1px solid #444}.nexus-memory-form textarea{min-height:90px}.nexus-memory-form .wide{grid-column:1/-1}@media(max-width:760px){.nexus-memory-grid,.nexus-memory-form{grid-template-columns:1fr 1fr}}@media(max-width:520px){.nexus-memory-grid,.nexus-memory-form{grid-template-columns:1fr}.nexus-memory-form .wide{grid-column:auto}}';document.head.appendChild(s);}
function countsHTML(c){var types=['fact','decision','recommendation','conflict'];return'<div class="nexus-memory-grid">'+types.map(function(k){return'<div class="nexus-memory-card"><strong>'+esc(c[k]||0)+'</strong><span>'+esc(k)+'</span></div>';}).join('')+'</div>';}
function formHTML(){return'<form id="nexus-memory-form" class="nexus-memory-form"><label>Type<select name="memory_type"><option>decision</option><option>fact</option><option>assumption</option><option>source</option><option>calculation</option><option>recommendation</option><option>conflict</option><option>unknown</option></select></label><label>Product ID<input name="product_id" placeholder="community-connect"></label><label>Stable key<input name="memory_key" required placeholder="decision.community-connect.positioning"></label><label class="wide">Title<input name="title" required maxlength="240"></label><label class="wide">Structured memory<textarea name="content" required maxlength="12000" placeholder="Record the decision/fact itself. Do not paste private conversations."></textarea></label><label>Confidence<select name="confidence"><option>NOT_ASSESSED</option><option>HIGH</option><option>MEDIUM</option><option>LOW</option></select></label><label>Reference date<input name="reference_date" type="date"></label><label>Source URL<input name="source_url" type="url" placeholder="https://"></label><div class="wide"><button type="submit" class="command-primary">Record institutional memory</button></div></form><p class="command-feedback" id="nexus-memory-feedback">Explicit structured records only. Raw conversations are never auto-saved here.</p>';}
async function decorate(){if(busy||!root||!root.querySelector('.command-hero')||document.getElementById('nexus-memory-panel'))return;busy=true;style();try{var data=await rpc('ibis_memory_snapshot',{p_product_id:null,p_limit:20}),panel=document.createElement('section');panel.id='nexus-memory-panel';panel.className='command-panel command-panel--wide';panel.innerHTML='<div class="command-panel__head"><div><span>IBIS-AI INSTITUTIONAL MEMORY</span><h2>Decisions, facts and evidence FTN can deliberately retain</h2></div></div><p class="command-copy">Founder-controlled structured memory. Every write is audited; chats are not silently stored in this ledger.</p>'+countsHTML(data.counts||{})+'<div class="nexus-memory-list">'+(data.items||[]).slice(0,8).map(function(x){return'<article class="nexus-memory-row"><h3>'+esc(x.title)+'</h3><p>'+esc(x.memory_type)+' · '+esc(x.product_id||'ecosystem')+' · '+esc(x.confidence)+' · '+esc(x.status)+'</p><p>'+esc(x.content)+'</p>'+(x.source_url?'<a href="'+esc(x.source_url)+'" target="_blank" rel="noopener noreferrer">Source ↗</a>':'')+'</article>';}).join('')+'</div>'+formHTML();(root.querySelector('.command-columns')||root.querySelector('.command-view')).appendChild(panel);var f=document.getElementById('nexus-memory-form');f.onsubmit=async function(e){e.preventDefault();var out=document.getElementById('nexus-memory-feedback'),v=function(n){return f.elements[n].value.trim();};out.textContent='Recording audited institutional memory…';try{await rpc('ibis_memory_upsert',{p_memory_key:v('memory_key'),p_memory_type:v('memory_type'),p_title:v('title'),p_content:v('content'),p_product_id:v('product_id')||null,p_source_url:v('source_url')||null,p_reference_date:v('reference_date')||null,p_retrieved_at:v('source_url')?new Date().toISOString():null,p_confidence:v('confidence'),p_status:'active',p_metadata:{recorded_via:'nexus-command',automatic_chat_ingest:false}});out.textContent='Recorded. Reload Nexus Command to refresh the memory list.';f.reset();}catch(err){out.textContent='Memory was not recorded. Owner authorization or field validation failed.';}};}catch(e){}finally{busy=false;}}
var obs=new MutationObserver(function(){setTimeout(decorate,80);});if(root)obs.observe(root,{childList:true,subtree:true});document.addEventListener('DOMContentLoaded',function(){setTimeout(decorate,500);});
})(window);
