(function(global){'use strict';var list=(global.FTN&&global.FTN.CaribbeanParliaments)||[],current='tt',userChanged=false;
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function source(id){return list.filter(function(x){return x.id===id;})[0]||list[0];}
function watch(item){var mount=document.getElementById('parliament-watch');if(!mount)return;
var copy=document.getElementById('parliament-country-copy');if(copy)copy.textContent=item.country+(userChanged?' is selected. ':' is selected by default. ')+'Official live coverage takes priority when verified; otherwise FTN shows the latest verified official archive without downloading or mirroring it.';
var stateLabel=item.state==='LIVE'?'LIVE':'OFFLINE · LATEST OFFICIAL ARCHIVE';
var stateClass='parl-state'+(item.state==='LIVE'?' ftn-pulse':'');
var original=item.latest?item.latest.url:(item.videoUrl||item.liveUrl||item.officialUrl);
var linksHTML=(original?'<a href="'+esc(original)+'" target="_blank" rel="noopener noreferrer">Open original official source ↗</a>':'')+(item.videoUrl&&item.videoUrl!==original?'<a href="'+esc(item.videoUrl)+'" target="_blank" rel="noopener noreferrer">Official video channel ↗</a>':'')+(item.officialUrl?'<a href="'+esc(item.officialUrl)+'" target="_blank" rel="noopener noreferrer">Legislature website ↗</a>':'');
if(item.latest){
var media='<iframe title="Latest official '+esc(item.legislature)+' video" src="https://www.youtube-nocookie.com/embed/'+esc(item.latest.videoId)+'?rel=0&playsinline=1" allow="encrypted-media; picture-in-picture" allowfullscreen loading="eager"></iframe>';
mount.innerHTML='<div class="parl-player">'+media+'<div class="parl-player__meta"><span class="'+stateClass+'">'+esc(stateLabel)+'</span><h2>'+esc(item.latest.title)+'</h2><p>'+esc(item.country)+' · '+esc(item.legislature)+' · Published '+esc(item.latest.published)+' · Source checked '+esc(item.verified)+'. FTN does not download, mirror or alter publisher video.</p><div class="parl-source-actions">'+linksHTML+'</div></div></div>';
}else{
// No known sitting/embed metadata at all -- render one compact source-identity card (publisher,
// verification date, official links) rather than a tall empty player void with the explanation
// as its only content. The "not available" state is one subordinate sentence, not the hero.
mount.innerHTML='<div class="parl-player parl-player--source-card"><div class="parl-player__meta"><span class="'+stateClass+'">'+esc(stateLabel)+'</span><h2>'+esc(item.country)+' — '+esc(item.legislature)+'</h2><p>Source checked '+esc(item.verified)+'. FTN does not download, mirror or alter publisher video.</p><div class="parl-source-actions">'+linksHTML+'</div><p class="parl-player__note">No verified embeddable stream is available here.</p></div></div>';
}
document.getElementById('parliament-watch-status').textContent=item.state==='LIVE'?'An official live source is available.':'No current official live stream was verified at the last check; showing the latest verified official archive or an honest source fallback.';}
function card(item){return'<article class="parl-source-card"><div class="parl-source-card__meta"><span>'+esc(item.state)+'</span><span>'+esc(item.chambers)+'</span></div><h3>'+esc(item.country)+'</h3><p><strong>'+esc(item.legislature)+'</strong><br>'+esc(item.confidence)+' · Checked '+esc(item.verified)+'</p><div class="parl-source-card__actions"><button type="button" data-country="'+esc(item.id)+'">Watch / inspect</button>'+(item.officialUrl?'<a href="'+esc(item.officialUrl)+'" target="_blank" rel="noopener noreferrer">Official site ↗</a>':'<span>Official public source unavailable</span>')+(item.videoUrl?'<a href="'+esc(item.videoUrl)+'" target="_blank" rel="noopener noreferrer">Official video ↗</a>':'')+'</div></article>';}
function catalogue(){var mount=document.getElementById('parliament-catalogue');mount.innerHTML=list.map(card).join('');mount.querySelectorAll('[data-country]').forEach(function(button){button.onclick=function(){userChanged=true;current=button.dataset.country;document.getElementById('parliament-country').value=current;watch(source(current));document.getElementById('watch-now').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});};});document.getElementById('parliament-catalogue-status').textContent=list.length+' Caribbean legislatures and distinct territorial assemblies recorded · '+list.filter(function(x){return x.videoUrl||x.liveUrl;}).length+' with verified official video or live destinations.';}
function init(){var select=document.getElementById('parliament-country');select.innerHTML=list.map(function(x){return'<option value="'+esc(x.id)+'"'+(x.id==='tt'?' selected':'')+'>'+esc(x.country)+'</option>';}).join('');select.onchange=function(){userChanged=true;current=select.value;watch(source(current));};watch(source(current));catalogue();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();})(window);
