// FTN Radio — live YouTube-backed station/discovery player.
(function(global){'use strict';
  function $(s,r){return (r||document).querySelector(s);}function esc(s){return String(s||'').replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
  function init(){
    var host=$('.radio-listen');if(!host||!global.FTN||!global.FTN.MediaDiscovery)return;
    var genres=[['soca','Soca'],['reggae','Reggae & Roots'],['dancehall','Dancehall'],['zouk-kompa','Zouk / Kompa'],['chutney','Chutney Soca'],['calypso','Calypso / Kaiso'],['steelpan','Steelpan'],['gospel','Gospel']];
    var shell=document.createElement('div');shell.className='ftn-radio-live';shell.innerHTML='<style>.ftn-radio-live{margin-top:20px;display:grid;grid-template-columns:minmax(260px,.75fr) minmax(0,1.25fr);gap:14px}.ftn-radio-live__player{border:1px solid rgba(255,255,255,.14);border-radius:18px;overflow:hidden;background:#050607}.ftn-radio-live__video{aspect-ratio:16/9;background:#000}.ftn-radio-live__video>div,.ftn-radio-live__video iframe{width:100%!important;height:100%!important}.ftn-radio-live__now{padding:13px}.ftn-radio-live__now strong{display:block;font-size:16px}.ftn-radio-live__now span{display:block;color:#aeb5c0;margin-top:4px}.ftn-radio-live__controls{display:flex;gap:7px;margin-top:10px}.ftn-radio-live__controls button{flex:1}.ftn-radio-live__catalog{min-width:0}.ftn-radio-live__genres{display:flex;gap:6px;overflow:auto;padding-bottom:8px}.ftn-radio-live__genres button{white-space:nowrap}.ftn-radio-live__tracks{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:6px;max-height:430px;overflow:auto}.ftn-radio-live__track{display:grid;grid-template-columns:58px 1fr;gap:8px;text-align:left;padding:6px;border:1px solid rgba(255,255,255,.12);border-radius:10px;background:#10141a;color:#fff;cursor:pointer}.ftn-radio-live__track img{width:58px;height:58px;object-fit:cover;border-radius:7px}.ftn-radio-live__track strong{font-size:11px;line-height:1.2}.ftn-radio-live__track span{font-size:9px;color:#98a1ae}.ftn-radio-live__status{color:#9ea7b4;font-size:11px;margin:7px 0}@media(max-width:760px){.ftn-radio-live{grid-template-columns:1fr}.ftn-radio-live__player{position:sticky;top:0;z-index:15}.ftn-radio-live__tracks{grid-template-columns:1fr 1fr;max-height:330px}.ftn-radio-live__track{grid-template-columns:44px 1fr}.ftn-radio-live__track img{width:44px;height:44px}}</style><div class="ftn-radio-live__player"><div class="ftn-radio-live__video"><div id="ftn-radio-yt"></div></div><div class="ftn-radio-live__now"><strong id="ftn-radio-title">Loading FTN Radio…</strong><span id="ftn-radio-artist">Caribbean discovery</span><div class="ftn-radio-live__controls"><button type="button" id="ftn-radio-play" class="btn btn-primary">PLAY</button><button type="button" id="ftn-radio-next" class="btn btn-outline">NEXT</button></div></div></div><div class="ftn-radio-live__catalog"><div class="ftn-radio-live__genres">'+genres.map(function(g,i){return'<button type="button" class="btn btn-outline btn-sm" data-radio-genre="'+g[0]+'" aria-pressed="'+(i===0?'true':'false')+'">'+g[1]+'</button>';}).join('')+'</div><p class="ftn-radio-live__status" id="ftn-radio-status">Finding individual Caribbean tracks…</p><div class="ftn-radio-live__tracks" id="ftn-radio-tracks"></div></div>';
    host.appendChild(shell);
    var tracks=[],idx=0,player=null,ytReady=false,currentGenre='soca';
    function meta(){var t=tracks[idx];if(!t)return;$('#ftn-radio-title').textContent=t.title;$('#ftn-radio-artist').textContent=t.channel||'YouTube';}
    function playIndex(i,autoplay){if(!tracks.length)return;idx=(i+tracks.length)%tracks.length;meta();if(player&&ytReady){try{if(autoplay)player.loadVideoById(tracks[idx].videoId);else player.cueVideoById(tracks[idx].videoId);}catch(e){}}}
    function render(){var m=$('#ftn-radio-tracks');m.innerHTML=tracks.map(function(t,i){return'<button type="button" class="ftn-radio-live__track" data-radio-track="'+i+'"><img src="'+esc(t.thumbnail||'')+'" alt=""><span><strong>'+esc(t.title)+'</strong><span>'+esc(t.channel||'YouTube')+'</span></span></button>';}).join('');m.querySelectorAll('[data-radio-track]').forEach(function(b){b.addEventListener('click',function(){playIndex(+b.getAttribute('data-radio-track'),true);});});}
    function loadGenre(genre,force){currentGenre=genre;$('#ftn-radio-status').textContent='Tuning '+genre+'…';document.querySelectorAll('[data-radio-genre]').forEach(function(b){b.setAttribute('aria-pressed',String(b.getAttribute('data-radio-genre')===genre));});return global.FTN.MediaDiscovery.discover({mode:'music',genre:genre,limit:120},{force:!!force}).then(function(d){tracks=d.results||[];idx=0;render();playIndex(0,false);$('#ftn-radio-status').textContent=tracks.length+' embeddable individual tracks available · mixes excluded';}).catch(function(e){$('#ftn-radio-status').textContent=e.message;});}
    shell.addEventListener('click',function(e){var g=e.target.closest('[data-radio-genre]');if(g)loadGenre(g.getAttribute('data-radio-genre'),true);});
    $('#ftn-radio-play').addEventListener('click',function(){if(!player)return;try{var st=player.getPlayerState();if(st===YT.PlayerState.PLAYING){player.pauseVideo();this.textContent='PLAY';}else{player.playVideo();this.textContent='PAUSE';}}catch(e){}});$('#ftn-radio-next').addEventListener('click',function(){playIndex(idx+1,true);});
    global.onYouTubeIframeAPIReady=(function(previous){return function(){if(typeof previous==='function')try{previous();}catch(e){}ytReady=true;var id=tracks[0]&&tracks[0].videoId||'M7lc1UVf-VE';player=new YT.Player('ftn-radio-yt',{videoId:id,playerVars:{controls:1,rel:0,playsinline:1,origin:location.origin},events:{onReady:function(){if(tracks.length)playIndex(0,false);}}});};})(global.onYouTubeIframeAPIReady);
    if(!global.YT){var s=document.createElement('script');s.src='https://www.youtube.com/iframe_api';document.head.appendChild(s);}else if(global.YT.Player&&global.onYouTubeIframeAPIReady){global.onYouTubeIframeAPIReady();}
    loadGenre(currentGenre,false);
  }
  document.addEventListener('DOMContentLoaded',init);
})(window);
