// FTN Scarlett — adaptive, reversible website presentation engine.
// Local-first deterministic foundation. No fixed site archetypes; page purpose is inferred from live signals.
(function(global){
'use strict';
var FTN=global.FTN=global.FTN||{},doc=global.document,STATE_KEY='ftn-scarlett-v1',root=doc.documentElement;
var changed=[],active=false,intensity=78,goal='clarity';
var RULES={
  'SC-A11Y-FOCUS':{category:'accessibility',rationale:'Visible focus improves keyboard operability.'},
  'SC-READ-WIDTH':{category:'readability',rationale:'Bounded text measure improves scanning and reading.'},
  'SC-HIERARCHY':{category:'hierarchy',rationale:'Clear heading and spacing hierarchy reduces search cost.'},
  'SC-CTA-FOCUS':{category:'friction',rationale:'Prioritising existing primary actions reduces competing choices without inventing claims.'},
  'SC-STICKY-NOISE':{category:'friction',rationale:'Non-essential fixed chrome can obscure content and consume viewport space.'},
  'SC-BRAND-PRESERVE':{category:'trust',rationale:'Preserving source brand cues reduces identity discontinuity.'}
};
function text(el){return (el&&el.textContent||'').replace(/\s+/g,' ').trim();}
function visible(el){if(!el||!el.getBoundingClientRect)return false;var s=getComputedStyle(el),r=el.getBoundingClientRect();return s.display!=='none'&&s.visibility!=='hidden'&&Number(s.opacity||1)>0&&r.width>2&&r.height>2;}
function scorePurpose(){var body=(doc.title+' '+text(doc.body).slice(0,25000)).toLowerCase(),scores={commerce:0,service:0,editorial:0,civic:0,creator:0,utility:0};
  function hit(k,words,w){words.forEach(function(x){if(body.indexOf(x)>=0)scores[k]+=w||1;});}
  hit('commerce',['add to cart','checkout','shop','price','buy now','shipping','product'],2);
  hit('service',['book','appointment','services','contact us','request a quote','consultation'],2);
  hit('editorial',['article','author','published','news','opinion','read more'],2);
  hit('civic',['government','ministry','public notice','citizen','municipal','application form','policy'],2);
  hit('creator',['subscribe','watch','listen','episode','creator','artist','channel'],2);
  hit('utility',['dashboard','workspace','sign in','log in','search','account','settings'],1);
  var forms=doc.forms.length,products=doc.querySelectorAll('[itemtype*="Product"], [class*="product" i]').length,articles=doc.querySelectorAll('article').length;
  if(forms>1)scores.service++;if(products)scores.commerce+=2;if(articles>2)scores.editorial+=2;
  var winner='unknown',best=0;Object.keys(scores).forEach(function(k){if(scores[k]>best){winner=k;best=scores[k];}});return{purpose:winner,confidence:Math.min(.95,best/8),scores:scores};}
function primaryActions(){return Array.from(doc.querySelectorAll('a[href],button,input[type="submit"]')).filter(visible).map(function(el){var label=(el.getAttribute('aria-label')||el.value||text(el)).trim();var score=0,s=(label+' '+el.className).toLowerCase();if(/buy|book|start|join|sign up|apply|contact|subscribe|get|try|donate|checkout|submit/.test(s))score+=3;if(el.tagName==='BUTTON'||el.matches('input[type="submit"]'))score+=1;var r=el.getBoundingClientRect();if(r.top<innerHeight*1.2)score+=1;return{el:el,label:label.slice(0,120),score:score};}).sort(function(a,b){return b.score-a.score;}).slice(0,8);}
function trustSignals(){var body=text(doc.body).toLowerCase(),signals=[];[['contact','contact'],['privacy','privacy'],['terms','terms'],['refund','refund'],['security','security'],['about','about'],['verified','verified']].forEach(function(pair){if(body.indexOf(pair[1])>=0)signals.push(pair[0]);});return signals;}
function friction(){var issues=[],ctas=primaryActions();if(ctas.filter(function(x){return x.score>=3;}).length>5)issues.push({id:'too-many-primary-actions',severity:'medium'});Array.from(doc.querySelectorAll('p')).filter(visible).slice(0,60).forEach(function(p){if(p.getBoundingClientRect().width>900&&text(p).length>240)issues.push({id:'wide-reading-measure',severity:'low'});});var fixed=Array.from(doc.querySelectorAll('body *')).filter(function(el){if(!visible(el))return false;var s=getComputedStyle(el);return s.position==='fixed'||s.position==='sticky';}).slice(0,20);if(fixed.length>4)issues.push({id:'excessive-fixed-chrome',severity:'medium'});return issues;}
function neuralMesh(){return Array.from(doc.querySelectorAll('a[href],button,input,select,textarea,form')).filter(visible).slice(0,400).map(function(el,i){return{id:'sc-'+i,tag:el.tagName.toLowerCase(),role:el.getAttribute('role')||null,label:(el.getAttribute('aria-label')||el.getAttribute('name')||text(el)).slice(0,120),href:el.tagName==='A'?el.getAttribute('href'):null};});}
function brand(){var sample=[doc.body,doc.querySelector('header'),doc.querySelector('nav'),doc.querySelector('main')].filter(Boolean),colors=[],fonts=[];sample.forEach(function(el){var s=getComputedStyle(el);if(s.color)colors.push(s.color);if(s.backgroundColor)colors.push(s.backgroundColor);if(s.fontFamily)fonts.push(s.fontFamily);});return{colors:Array.from(new Set(colors)).slice(0,8),fonts:Array.from(new Set(fonts)).slice(0,4)};}
function analyze(){var p=scorePurpose();return{version:1,urlOrigin:location.origin,purpose:p.purpose,purposeConfidence:p.confidence,purposeScores:p.scores,actions:primaryActions().map(function(a){return{label:a.label,score:a.score};}),trustSignals:trustSignals(),friction:friction(),brand:brand(),neuralMeshCount:neuralMesh().length,reducedMotion:matchMedia('(prefers-reduced-motion: reduce)').matches,generatedAt:new Date().toISOString()};}
function remember(el){if(changed.some(function(x){return x.el===el;}))return;changed.push({el:el,style:el.getAttribute('style'),className:el.getAttribute('class'),scarlett:el.getAttribute('data-scarlett-role')});}
function applyRole(el,role){if(!el)return;remember(el);el.setAttribute('data-scarlett-role',role);}
function plan(model,userGoal){var ops=[{rule:'SC-A11Y-FOCUS',op:'root'},{rule:'SC-HIERARCHY',op:'root'},{rule:'SC-BRAND-PRESERVE',op:'root'}];if(model.friction.some(function(x){return x.id==='wide-reading-measure';}))ops.push({rule:'SC-READ-WIDTH',op:'reading'});var actions=primaryActions().filter(function(a){return a.score>=3;}).slice(0,2);actions.forEach(function(a,i){ops.push({rule:'SC-CTA-FOCUS',op:'action',el:a.el,rank:i+1});});return{model:model,goal:userGoal||'clarity',operations:ops,rules:ops.map(function(o){return{id:o.rule,meta:RULES[o.rule]};})};}
function ensureStyle(){if(doc.getElementById('scarlett-runtime-style'))return;var s=doc.createElement('style');s.id='scarlett-runtime-style';s.textContent='\nhtml[data-scarlett="on"]{--sc-intensity:.78;--sc-red:#ef3340;--sc-bg:rgba(8,8,10,.96);scroll-behavior:smooth}\nhtml[data-scarlett="on"] body{transition:background-color .55s ease,color .45s ease,filter .45s ease}\nhtml[data-scarlett="on"] :is(main,article,section){transition:transform .65s cubic-bezier(.22,1,.36,1),opacity .55s ease,background-color .45s ease,border-color .45s ease}\nhtml[data-scarlett="on"] [data-scarlett-role="primary-action"]{position:relative!important;z-index:2!important;box-shadow:0 0 0 2px color-mix(in srgb,var(--sc-red) calc(var(--sc-intensity)*100%),transparent)!important;transform:translateZ(0) scale(calc(1 + var(--sc-intensity)*.018))!important;transition:transform .45s cubic-bezier(.22,1,.36,1),box-shadow .4s ease!important}\nhtml[data-scarlett="on"] :is(p,li){max-width:72ch}\nhtml[data-scarlett="on"] :is(h1,h2,h3){text-wrap:balance;letter-spacing:-.018em}\nhtml[data-scarlett="on"] :focus-visible{outline:3px solid var(--sc-red)!important;outline-offset:3px!important}\nhtml[data-scarlett="on"][data-scarlett-dominance="scarlett"] body{background-image:linear-gradient(180deg,rgba(239,51,64,calc(var(--sc-intensity)*.025)),transparent 32rem)}\n@media(prefers-reduced-motion:reduce){html[data-scarlett="on"] *,html[data-scarlett="on"] *::before,html[data-scarlett="on"] *::after{transition-duration:.01ms!important;animation-duration:.01ms!important;scroll-behavior:auto!important}}';doc.head.appendChild(s);}
function render(thePlan,value){ensureStyle();intensity=Math.max(0,Math.min(100,Number(value==null?intensity:value)));root.dataset.scarlett='on';root.style.setProperty('--sc-intensity',(intensity/100).toFixed(2));root.dataset.scarlettDominance=intensity<45?'source':intensity>55?'scarlett':'crossover';thePlan.operations.forEach(function(op){if(op.op==='action'&&op.el)applyRole(op.el,'primary-action');});active=true;dispatchEvent(new CustomEvent('ScarlettChanged',{detail:{active:true,intensity:intensity,plan:thePlan}}));return thePlan;}
function restore(){changed.forEach(function(x){if(!x.el||!x.el.isConnected)return;if(x.style==null)x.el.removeAttribute('style');else x.el.setAttribute('style',x.style);if(x.className==null)x.el.removeAttribute('class');else x.el.setAttribute('class',x.className);if(x.scarlett==null)x.el.removeAttribute('data-scarlett-role');else x.el.setAttribute('data-scarlett-role',x.scarlett);});changed=[];delete root.dataset.scarlett;delete root.dataset.scarlettDominance;root.style.removeProperty('--sc-intensity');active=false;dispatchEvent(new CustomEvent('ScarlettChanged',{detail:{active:false,intensity:0}}));}
function setIntensity(v,settled){v=Math.max(0,Math.min(100,Number(v)));if(settled&&v>=45&&v<=55)v=v<50?44:56;intensity=v;root.style.setProperty('--sc-intensity',(v/100).toFixed(2));root.dataset.scarlettDominance=v<45?'source':v>55?'scarlett':'crossover';try{localStorage.setItem(STATE_KEY,JSON.stringify({intensity:v,goal:goal}));}catch(e){}return v;}
function transform(opts){opts=opts||{};goal=opts.goal||goal;var model=analyze(),thePlan=plan(model,goal);render(thePlan,opts.intensity);return{model:model,plan:thePlan};}
FTN.Scarlett={version:'0.1.0',analyze:analyze,plan:plan,transform:transform,restore:restore,setIntensity:setIntensity,neuralMesh:neuralMesh,rules:RULES,get active(){return active;},get intensity(){return intensity;}};
})(window);
