(function(global){
'use strict';
var cache=null;
var WEIGHTS={userValue:1,ecosystemValue:1.2,ownership:1.1,dataValue:1.1,economicValue:1.2,executionCost:1,futureOptionality:1,urgency:1.2,competitionGap:1.2};
var MAX=Object.values(WEIGHTS).reduce(function(a,b){return a+b;},0)*5;
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function score(f){var total=0,s=f.signals||{};Object.keys(WEIGHTS).forEach(function(k){var v=Number(s[k]||1);if(k==='executionCost')v=6-v;total+=v*WEIGHTS[k];});return Math.round(total/MAX*100);}
function priority(f){if(f.directive==='STRATEGIC_COLLISION'||f.status==='OPEN_URGENT')return'P0';var s=score(f);return s>=82?'P0':s>=70?'P1':s>=58?'P2':'WATCH';}
function daysTo(value){if(!value)return null;var d=new Date(value+'T23:59:59Z');if(isNaN(d))return null;return Math.ceil((d-Date.now())/86400000);}
async function load(){if(cache)return cache;var r=await fetch('/data/scout-2-current.json',{cache:'no-cache'});if(!r.ok)throw new Error('Scout registry unavailable');var d=await r.json();cache=d;return d;}
function filter(items,opt){opt=opt||{};return items.filter(function(f){if(opt.products&&opt.products.length&&!(f.ftnProducts||[]).some(function(p){return opt.products.indexOf(p)>=0;}))return false;if(opt.types&&opt.types.length&&opt.types.indexOf(f.type)<0)return false;if(opt.excludeClosed&&/^CLOSED/.test(f.status||''))return false;return true;}).map(function(f){var x=Object.assign({},f);x.score=score(f);x.priority=priority(f);x.daysToDeadline=daysTo(f.deadline);return x;}).sort(function(a,b){var p={P0:0,P1:1,P2:2,WATCH:3};return p[a.priority]-p[b.priority]||b.score-a.score;});}
function renderCard(f){var deadline=f.deadline?'<span class="scout-feed__deadline">'+(f.daysToDeadline!=null&&f.daysToDeadline>=0?esc(f.daysToDeadline+' days left · '):'')+esc(f.deadline)+'</span>':'';return '<article class="scout-feed__card"><div class="scout-feed__meta"><span>'+esc(f.priority)+'</span><span>'+esc(f.type)+'</span><span>'+esc(f.score)+'/100</span></div><h3>'+esc(f.title)+'</h3><p>'+esc(f.summary||f.whyFtn||'')+'</p>'+deadline+(f.deadlineConflict?'<p class="scout-feed__warning">Deadline/source conflict: verify before acting.</p>':'')+'<div class="scout-feed__foot"><strong>'+esc(f.directive)+'</strong><a href="'+esc(f.sourceUrl)+'" target="_blank" rel="noopener noreferrer">Verify source ↗</a></div><small>Verified '+esc(f.verifiedAt)+'</small></article>';}
function ensureStyle(){if(document.getElementById('scout-feed-style'))return;var s=document.createElement('style');s.id='scout-feed-style';s.textContent='.scout-feed{display:grid;gap:12px}.scout-feed__summary{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.scout-feed__metric,.scout-feed__card{border:1px solid rgba(255,255,255,.14);border-radius:12px;padding:14px;background:rgba(12,12,15,.74)}.scout-feed__metric strong{display:block;font-size:1.5rem}.scout-feed__cards{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}.scout-feed__card h3{font-size:1rem;margin:.55rem 0}.scout-feed__card p{font-size:.82rem;line-height:1.45}.scout-feed__meta{display:flex;gap:6px;flex-wrap:wrap}.scout-feed__meta span,.scout-feed__deadline{font-size:.68rem;border:1px solid rgba(255,255,255,.18);border-radius:999px;padding:3px 7px}.scout-feed__deadline{display:inline-block;margin:.2rem 0}.scout-feed__warning{color:#ffd0d3}.scout-feed__foot{display:flex;justify-content:space-between;gap:10px;align-items:center;margin-top:.7rem}.scout-feed__foot a{color:inherit}.scout-feed small{opacity:.72}@media(max-width:900px){.scout-feed__cards{grid-template-columns:repeat(2,minmax(0,1fr))}.scout-feed__summary{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:600px){.scout-feed__cards,.scout-feed__summary{grid-template-columns:1fr}}';document.head.appendChild(s);}
async function mount(el,opt){if(!el)return;ensureStyle();try{var d=await load(),items=filter(d.findings||[],opt),p0=items.filter(function(x){return x.priority==='P0';}),money=items.filter(function(x){return['MONEY','PROCUREMENT','ACCELERATOR','AWARD'].indexOf(x.type)>=0;}),collisions=items.filter(function(x){return x.directive==='STRATEGIC_COLLISION';}),urgent=items.filter(function(x){return x.daysToDeadline!=null&&x.daysToDeadline>=0&&x.daysToDeadline<=30;});el.innerHTML='<div class="scout-feed"><div class="scout-feed__summary"><div class="scout-feed__metric"><strong>'+items.length+'</strong><span>verified signals</span></div><div class="scout-feed__metric"><strong>'+p0.length+'</strong><span>P0 review</span></div><div class="scout-feed__metric"><strong>'+money.length+'</strong><span>money/institutional</span></div><div class="scout-feed__metric"><strong>'+urgent.length+'</strong><span>deadlines ≤30 days</span></div></div>'+(collisions.length?'<p><strong>'+collisions.length+' strategic collision'+(collisions.length===1?'':'s')+'</strong> must be addressed before overlapping builds.</p>':'')+'<div class="scout-feed__cards">'+items.slice(0,(opt&&opt.limit)||12).map(renderCard).join('')+'</div><small>Founder-reviewed baseline · run '+esc(d.runDate)+'. Scout recommends; it does not apply, spend or build automatically.</small></div>';return items;}catch(e){el.innerHTML='<p>Scout intelligence could not be loaded. No opportunity status is being inferred.</p>';return[];}}
global.FTN=global.FTN||{};global.FTN.ScoutFeed={load:load,filter:filter,mount:mount,score:score,priority:priority};
})(window);
