// FTN Screen — live, embeddable Caribbean film/video discovery using FTN media discovery service.
(function(global){'use strict';
  function $(s,r){return (r||document).querySelector(s);}function esc(s){return String(s||'').replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
  var DEFAULT_QUERIES=['Trinidad Tobago full movie official','Caribbean film full movie official','Trinidad film movie official','Tobago film documentary official','Machel Montano movie Trinidad','Omega Hammer Trinidad movie','No Bois Man No Fraid Trinidad film','Batchak Man Trinidad film'];
  function loadFestivalStudio(){if(document.querySelector('script[data-screen-festival-studio]'))return;var s=document.createElement('script');s.src='/js/screen-festival-studio.js';s.setAttribute('data-screen-festival-studio','true');document.head.appendChild(s);}
  function init(){var hero=$('.screen-hero');if(!hero||!global.FTN||!global.FTN.MediaDiscovery){loadFestivalStudio();return;}var section=document.createElement('section');section.className='screen-panel screen-catalog';section.innerHTML='<style>.screen-catalog{margin-top:18px}.screen-catalog__layout{display:grid;grid-template-columns:minmax(280px,.9fr) minmax(0,1.1fr);gap:14px}.screen-catalog__viewer{border:1px solid rgba(255,255,255,.14);border-radius:16px;overflow:hidden;background:#050506}.screen-catalog__video{aspect-ratio:16/9;background:#000}.screen-catalog__video iframe{width:100%;height:100%;border:0}.screen-catalog__meta{padding:13px}.screen-catalog__meta strong{display:block;font-size:17px}.screen-catalog__meta span{display:block;color:#a7aeba;margin-top:4px}.screen-catalog__tools{display:flex;gap:7px;margin:10px 0}.screen-catalog__tools input{flex:1;min-width:0;background:#0c0f14;color:#fff;border:1px solid #343b45;border-radius:9px;padding:9px}.screen-catalog__grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:7px;max-height:520px;overflow:auto}.screen-catalog__item{display:grid;grid-template-columns:86px 1fr;gap:8px;padding:7px;text-align:left;background:#10141a;color:#fff;border:1px solid rgba(255,255,255,.12);border-radius:10px;cursor:pointer}.screen-catalog__item img{width:86px;height:58px;object-fit:cover;border-radius:6px}.screen-catalog__item strong{font-size:11px;line-height:1.2}.screen-catalog__item span{display:block;color:#98a1ae;font-size:9px;margin-top:4px}.screen-catalog__status{font-size:11px;color:#9ea7b4}@media(max-width:760px){.screen-catalog__layout{grid-template-columns:1fr}.screen-catalog__viewer{position:sticky;top:0;z-index:20}.screen-catalog__grid{grid-template-columns:1fr 1fr;max-height:380px}.screen-catalog__item{grid-template-columns:58px 1fr}.screen-catalog__item img{width:58px;height:44px}}</style><span class="screen-kicker">Watch Caribbean</span><h3>Caribbean film discovery</h3><p class="workspace-muted">FTN searches embeddable public YouTube video sources and keeps the original creator/channel attribution. Search results are not presented as FTN-owned films.</p><div class="screen-catalog__tools"><input id="screen-search" type="search" placeholder="Search a Caribbean film, filmmaker or title"><button id="screen-search-btn" class="btn btn-primary" type="button">Search</button></div><p class="screen-catalog__status" id="screen-catalog-status">Finding Caribbean film and documentary sources…</p><div class="screen-catalog__layout"><div class="screen-catalog__viewer"><div class="screen-catalog__video"><iframe id="screen-catalog-frame" title="FTN Screen player" allow="autoplay; encrypted-media; picture-in-picture" allowfullscreen></iframe></div><div class="screen-catalog__meta"><strong id="screen-catalog-title">Choose a film</strong><span id="screen-catalog-channel">Source attribution appears here</span></div></div><div class="screen-catalog__grid" id="screen-catalog-grid"></div></div>';
    hero.insertAdjacentElement('afterend',section);var items=[];
    function play(i){var t=items[i];if(!t)return;$('#screen-catalog-frame').src='https://www.youtube.com/embed/'+encodeURIComponent(t.videoId)+'?autoplay=1&rel=0&playsinline=1';$('#screen-catalog-title').textContent=t.title;$('#screen-catalog-channel').textContent=t.channel||'YouTube';}
    function render(){var grid=$('#screen-catalog-grid');grid.innerHTML=items.map(function(t,i){return'<button class="screen-catalog__item" type="button" data-screen-video="'+i+'"><img src="'+esc(t.thumbnail||'')+'" alt=""><span><strong>'+esc(t.title)+'</strong><span>'+esc(t.channel||'YouTube')+'</span></span></button>';}).join('');grid.querySelectorAll('[data-screen-video]').forEach(function(b){b.addEventListener('click',function(){play(+b.getAttribute('data-screen-video'));});});if(items.length){$('#screen-catalog-title').textContent=items[0].title;$('#screen-catalog-channel').textContent=(items[0].channel||'YouTube')+' · choose a title to load the authorized embed';$('#screen-catalog-frame').removeAttribute('src');}}
    function discover(queries){$('#screen-catalog-status').textContent='Searching embeddable Caribbean film sources…';global.FTN.MediaDiscovery.discover({mode:'video',queries:queries,limit:120},{force:true}).then(function(d){var total=(d.results||[]).length;items=(d.results||[]).slice(0,16);render();$('#screen-catalog-status').textContent=items.length+' of '+total+' embeddable video results shown. Refine the search for more.';}).catch(function(e){$('#screen-catalog-status').textContent=e.message;});}
    $('#screen-search-btn').addEventListener('click',function(){var q=$('#screen-search').value.trim();if(q)discover([q+' Caribbean film',q+' Trinidad Tobago movie',q+' official movie']);});$('#screen-search').addEventListener('keydown',function(e){if(e.key==='Enter'){e.preventDefault();$('#screen-search-btn').click();}});discover(DEFAULT_QUERIES);loadFestivalStudio();
  }
  document.addEventListener('DOMContentLoaded',init);
})(window);
