// FTN Top Picks — public, disclosure-first view of the FTN Relationship Registry.
(function(global){'use strict';
function esc(v){return String(v||'').replace(/[&<>"']/g,function(c){return({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c];});}
function badge(item){if(item.relationshipType==='affiliate'&&item.status==='confirmed')return 'Affiliate';if(item.relationshipType==='support')return 'Support FTN';if(item.providerClass==='connected-provider')return 'Connected tool';return 'Useful destination';}
function init(){var root=document.getElementById('top-picks-root');if(!root)return;var reg=global.FTN&&global.FTN.RelationshipRegistry;if(!reg){setTimeout(init,100);return;}var rows=reg.all().filter(function(x){return x.publicUrl;});
root.innerHTML='<section class="page-hero"><div class="container"><span class="page-hero__eyebrow">FTN Top Picks</span><h1 class="page-hero__title">Useful tools. Caribbean context. Clear disclosure.</h1><p class="page-hero__lede">FTN highlights services that can genuinely help creators, businesses and communities. We prefer useful free options and Caribbean availability. Affiliate commission never determines the recommendation.</p></div></section><section class="section"><div class="container"><div class="section__header"><span class="section__eyebrow">Tools & destinations</span><h2>Start with what you need to accomplish.</h2></div><div class="module-grid">'+rows.map(function(item){var caps=(item.capabilities||[]).slice(0,4).join(' · ');var disclosure=item.disclosure||'External service. Check current availability, pricing and terms before relying on it.';return '<a class="module-card" href="'+esc(item.publicUrl)+'" target="_blank" rel="noopener noreferrer"><span class="module-card__eyebrow">'+esc(badge(item))+'</span><h3>'+esc(item.name)+'</h3><p>'+esc(caps||'External capability')+'</p><small>'+esc(disclosure)+'</small></a>';}).join('')+'</div></div></section><section class="section section--dark"><div class="container"><div class="section__header"><span class="section__eyebrow">How FTN ranks tools</span><h2>Value first. Commission second.</h2></div><div class="benefit-columns"><div class="benefit-column benefit-column--on-dark"><h3>Caribbean usefulness</h3><p>We look for practical access, free tiers or reasonable cost, creator/business value and whether the service can actually be used from the Caribbean.</p></div><div class="benefit-column benefit-column--on-dark"><h3>Transparent relationships</h3><p>If FTN may earn a referral commission, the relationship is disclosed. A paid relationship does not guarantee a recommendation.</p></div></div></div></section>';
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})(window);
