// FTN TV — data-driven television guide. Schedule records are FTN-owned programming metadata.
(function (global) {
  'use strict';
  var TZ='America/Port_of_Spain';
  var DAYS=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
  var BLOCKS=[
    {start:'06:00',end:'09:00',title:'Caribbean Morning',type:'Programming block',description:'Morning information, culture and community programming.'},
    {start:'09:00',end:'12:00',title:'Caribbean Life',type:'Programming block',description:'Food, travel, people, heritage and lifestyle programming.'},
    {start:'12:00',end:'14:00',title:'FTN Daytime',type:'Programming block',description:'Interviews, public-interest features and useful Caribbean information.'},
    {start:'14:00',end:'17:00',title:'Caribbean Screen',type:'Programming block',description:'Films, documentaries and shorts supplied through FTN Screen when rights are confirmed.'},
    {start:'17:00',end:'19:00',title:'Caribbean Now',type:'Programming block',description:'Newsroom, community and current-affairs programming.'},
    {start:'19:00',end:'20:00',title:'Face The Nation',type:'FTN programme',description:'FTN public affairs and national conversation.'},
    {start:'20:00',end:'22:00',title:'Prime Caribbean',type:'Programming block',description:'Prime-time Caribbean films, series and specials when programming is confirmed.'},
    {start:'22:00',end:'00:00',title:'Island Nights',type:'Programming block',description:'Music, culture, conversation and late-night Caribbean programming.'}
  ];

  function minutes(s){var p=s.split(':');return (+p[0])*60+(+p[1]);}
  function atlanticParts(date){var parts=new Intl.DateTimeFormat('en-CA',{timeZone:TZ,weekday:'long',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(date);var o={};parts.forEach(function(p){o[p.type]=p.value;});return o;}
  function nowMinutes(){var p=atlanticParts(new Date());return (+p.hour)*60+(+p.minute);}
  function todayName(){return atlanticParts(new Date()).weekday;}
  function currentBlock(){var m=nowMinutes();return BLOCKS.find(function(b){var s=minutes(b.start),e=b.end==='00:00'?1440:minutes(b.end);return m>=s&&m<e;})||BLOCKS[0];}
  function nextBlock(){var cur=currentBlock();var i=BLOCKS.indexOf(cur);return BLOCKS[(i+1)%BLOCKS.length];}
  function formatTime(s){var h=+s.slice(0,2),m=s.slice(3);if(s==='00:00')return '12:00 AM';var suffix=h>=12?'PM':'AM';h=h%12||12;return h+':'+m+' '+suffix;}
  function dateForOffset(offset){var d=new Date();d.setDate(d.getDate()+offset);return d;}
  function renderDay(container,dayOffset){var d=dateForOffset(dayOffset);var p=atlanticParts(d);container.innerHTML='<div class="tv-guide__date"><strong>'+p.weekday+'</strong><span>'+p.month+'/'+p.day+'/'+p.year+' · Atlantic Time</span></div><div class="tv-guide__rows">'+BLOCKS.map(function(b){return '<article class="tv-guide__row"><time>'+formatTime(b.start)+'</time><div><span>'+b.type+'</span><h3>'+b.title+'</h3><p>'+b.description+'</p></div></article>';}).join('')+'</div><p class="tv-guide__note">Programming blocks define the station clock. Specific external films, series or creator programmes appear only after source, rights and schedule confirmation.</p>';}
  function injectStyles(){var s=document.createElement('style');s.textContent='.tv-shell{background:#08090b;color:#fff;min-height:70vh;padding:48px 0 80px}.tv-wrap{width:min(1180px,calc(100% - 32px));margin:auto}.tv-kicker{color:#e94750;font:800 12px/1 Inter,sans-serif;letter-spacing:.12em;text-transform:uppercase}.tv-hero{display:grid;grid-template-columns:1.3fr .7fr;gap:32px;align-items:end;padding:36px 0}.tv-hero h1{font:800 clamp(38px,6vw,78px)/.95 Montserrat,sans-serif;margin:8px 0 14px}.tv-hero p{color:#a1a1a1;max-width:60ch}.tv-signal{height:170px;border:1px solid #2f3238;border-radius:18px;background:repeating-linear-gradient(0deg,#101216 0 2px,#0a0b0d 2px 5px);display:grid;place-items:center;position:relative;overflow:hidden}.tv-signal:after{content:"FTN TV";font:800 36px Montserrat;color:#fff}.tv-now{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin:20px 0 28px}.tv-now article{border:1px solid #30343a;border-radius:14px;background:#111318;padding:18px}.tv-now span,.tv-guide__row span{color:#e94750;font-size:11px;font-weight:800;text-transform:uppercase;letter-spacing:.08em}.tv-now h2{margin:5px 0 5px;font-size:22px}.tv-tabs{display:flex;gap:7px;overflow:auto;padding:4px 0 14px}.tv-tabs button{white-space:nowrap;border:1px solid #343840;border-radius:999px;background:#111318;color:#fff;padding:9px 13px;font-weight:700;cursor:pointer}.tv-tabs button[aria-current="true"]{background:#e10613;border-color:#e10613}.tv-guide{border-top:1px solid #30343a}.tv-guide__date{display:flex;justify-content:space-between;gap:12px;padding:18px 0;border-bottom:1px solid #25282d}.tv-guide__date span{color:#a1a1a1;font-size:12px}.tv-guide__row{display:grid;grid-template-columns:100px 1fr;gap:16px;padding:16px 0;border-bottom:1px solid #25282d}.tv-guide__row time{font-weight:800}.tv-guide__row h3{margin:4px 0}.tv-guide__row p{margin:0;color:#a1a1a1}.tv-guide__note{color:#8a9098;font-size:11px;line-height:1.5;margin-top:16px}@media(max-width:700px){.tv-hero{grid-template-columns:1fr}.tv-now{grid-template-columns:1fr}.tv-guide__row{grid-template-columns:78px 1fr}.tv-signal{height:120px}}';document.head.appendChild(s);}
  function init(){injectStyles();var root=document.getElementById('ftn-tv-root');if(!root)return;var now=currentBlock(),next=nextBlock();root.innerHTML='<section class="tv-shell"><div class="tv-wrap"><div class="tv-hero"><div><span class="tv-kicker">FTN TV · Caribbean Television Network</span><h1>Caribbean television, programmed with purpose.</h1><p>FTN TV is the scheduled television network. FTN Screen supplies movies and cinema; FTN TV decides what airs when and presents the station guide.</p></div><div class="tv-signal" aria-hidden="true"></div></div><div class="tv-now"><article><span>Now · '+todayName()+'</span><h2>'+now.title+'</h2><p>'+formatTime(now.start)+'–'+formatTime(now.end)+' Atlantic · '+now.description+'</p></article><article><span>Up Next</span><h2>'+next.title+'</h2><p>'+formatTime(next.start)+'–'+formatTime(next.end)+' Atlantic · '+next.description+'</p></article></div><div class="tv-tabs" aria-label="TV guide days"></div><div class="tv-guide" aria-live="polite"></div></div></section>';
    var tabs=root.querySelector('.tv-tabs'),guide=root.querySelector('.tv-guide');for(var i=0;i<7;i++){(function(offset){var d=dateForOffset(offset),p=atlanticParts(d),b=document.createElement('button');b.type='button';b.textContent=offset===0?'Today':p.weekday.slice(0,3)+' '+p.month+'/'+p.day;b.setAttribute('aria-current',offset===0?'true':'false');b.addEventListener('click',function(){tabs.querySelectorAll('button').forEach(function(x){x.setAttribute('aria-current','false');});b.setAttribute('aria-current','true');renderDay(guide,offset);});tabs.appendChild(b);})(i);}renderDay(guide,0);
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
  global.FTN=global.FTN||{};global.FTN.TVGuide={blocks:BLOCKS.slice(),timeZone:TZ,current:currentBlock,next:nextBlock};
})(window);
