import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const ALLOWED=new Set(["https://ftnplatform.org","https://www.ftnplatform.org","http://localhost:3000","http://127.0.0.1:3000"]);
const SOURCES={caricom:"https://caricom.org/vacancies/",cdb:"https://www.caribank.org/work-with-us/procurement/procurement-notices",cdbGeneral:"https://www.caribank.org/work-with-us/procurement/general-procurement-notices"};
function origin(req:Request){const o=req.headers.get("origin")||"",r=req.headers.get("referer")||"";if(o&&ALLOWED.has(o))return o;for(const a of ALLOWED)if(r.startsWith(a+"/"))return a;return"";}
function validKey(req:Request){const k=req.headers.get("apikey")||"";try{const p=JSON.parse(Deno.env.get("SUPABASE_PUBLISHABLE_KEYS")||"{}");return !!k&&Object.values(p).includes(k);}catch{return false;}}
function hdr(o:string){return{"content-type":"application/json; charset=utf-8","access-control-allow-origin":o||"https://ftnplatform.org","access-control-allow-methods":"GET,OPTIONS","access-control-allow-headers":"apikey,content-type","vary":"Origin","cache-control":"public, max-age=900, stale-while-revalidate=1800"};}
function json(req:Request,b:unknown,s=200){return new Response(JSON.stringify(b),{status:s,headers:hdr(origin(req))});}
function decode(v:string){return v.replace(/&amp;/g,"&").replace(/&#8211;|&ndash;/g,"–").replace(/&#8217;|&rsquo;/g,"’").replace(/&#038;/g,"&").replace(/&quot;/g,'"').replace(/&#039;/g,"'").replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim();}
function abs(base:string,u:string){try{return new URL(u,base).href}catch{return base}}
function inferType(title:string){const s=title.toLowerCase();if(/scholar|fellow/.test(s))return"Scholarship / Fellowship";if(/grant|fund/.test(s))return"Grant / Funding";if(/bid|tender|procure|supply|construction|consult/.test(s))return"Procurement / Consultancy";if(/vacan|officer|specialist|counsel|rapporteur|manager|director|attendant|economist|engineer/.test(s))return"Job / Employment";return"Opportunity";}
async function fetchText(url:string){const r=await fetch(url,{headers:{"user-agent":"FTN Platform Opportunities/1.0 (+https://ftnplatform.org/opportunities/)"}});if(!r.ok)throw new Error(`${new URL(url).hostname} ${r.status}`);return await r.text();}
function parseCARICOM(html:string){const out:any[]=[];const anchors=[...html.matchAll(/<a\s+[^>]*href=["']([^"']*\/opportunities\/[^"'#?]+\/?)["'][^>]*>([\s\S]*?)<\/a>/gi)];const seen=new Set<string>();for(const m of anchors){const title=decode(m[2]);const url=abs(SOURCES.caricom,m[1]);if(!title||title.length<4||seen.has(url)||/details|apply now|download/i.test(title))continue;seen.add(url);const pos=Math.max(0,m.index!-800),near=decode(html.slice(pos,m.index!+800));const closing=(near.match(/Closing Date:\s*([^|]{3,40})/i)||near.match(/Closing Date\s*:?\s*([A-Z][a-z]+\s+\d{1,2},?\s+\d{4})/i)||[])[1]||null;out.push({id:"caricom-"+out.length,title,organization:"CARICOM Secretariat",country:"Regional / CARICOM",type:inferType(title),deadline:closing,sourceUrl:url,sourceName:"CARICOM",official:true,lastVerified:new Date().toISOString(),summary:"Official CARICOM opportunity. Open the source for qualifications, terms and application instructions."});if(out.length>=20)break;}return out;}
function parseCDB(html:string,general=false){const out:any[]=[];const rowRe=/<tr[^>]*>([\s\S]*?)<\/tr>/gi;let m;while((m=rowRe.exec(html))){const row=m[1];const cells=[...row.matchAll(/<td[^>]*>([\s\S]*?)<\/td>/gi)].map(x=>decode(x[1]));if(cells.length<(general?3:4))continue;const a=row.match(/<a\s+[^>]*href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/i);const title=decode(a?.[2]||cells[0]||"");if(!title||/Role\/Service|Project Name/i.test(title))continue;const country=general?(cells[2]||"Regional"):(cells[2]||"Regional");const deadline=general?null:(cells[4]||cells[cells.length-1]||null);out.push({id:(general?"cdb-gpn-":"cdb-")+out.length,title,organization:"Caribbean Development Bank / executing agency",country,type:general?"General Procurement Notice":(cells[3]||inferType(title)),sector:cells[1]||null,deadline,sourceUrl:a?abs(SOURCES.cdb,a[1]):(general?SOURCES.cdbGeneral:SOURCES.cdb),sourceName:"Caribbean Development Bank",official:true,lastVerified:new Date().toISOString(),summary:general?"Official CDB general procurement notice. Open the source for expected contracts and eligibility.":"Official CDB procurement notice. Open the source for eligibility, terms and submission instructions."});if(out.length>=40)break;}return out;}
Deno.serve(async req=>{const o=origin(req);if(req.method==="OPTIONS")return new Response(null,{status:o?204:403,headers:hdr(o)});if(req.method!=="GET")return json(req,{error:"GET required"},405);if(!o)return json(req,{error:"Origin not allowed"},403);if(!validKey(req))return json(req,{error:"Invalid FTN client key"},401);const settled=await Promise.allSettled([fetchText(SOURCES.caricom),fetchText(SOURCES.cdb),fetchText(SOURCES.cdbGeneral)]);let items:any[]=[];const warnings:string[]=[];if(settled[0].status==="fulfilled")items.push(...parseCARICOM(settled[0].value));else warnings.push("CARICOM source unavailable");if(settled[1].status==="fulfilled")items.push(...parseCDB(settled[1].value,false));else warnings.push("CDB procurement source unavailable");if(settled[2].status==="fulfilled")items.push(...parseCDB(settled[2].value,true));else warnings.push("CDB general procurement source unavailable");const dedup=new Map<string,any>();for(const item of items){const key=(item.title+"|"+item.country).toLowerCase();if(!dedup.has(key))dedup.set(key,item);}items=[...dedup.values()];return json(req,{items,count:items.length,sources:[{name:"CARICOM",url:SOURCES.caricom},{name:"Caribbean Development Bank Procurement",url:SOURCES.cdb},{name:"CDB General Procurement Notices",url:SOURCES.cdbGeneral}],warnings,fetchedAt:new Date().toISOString(),notice:"FTN indexes official source metadata for discovery. Applicants must verify current eligibility, deadlines and instructions on the official source before acting."});});
