import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { addEvidence, createReasoningState, evidenceSummary, providerReasoningDirective, researchSourcePlan, sourceScores, type CebosEvidenceStatus, type CebosSourceClass } from "../_shared/ibis-cebos.ts";
import { scanOpportunitySignals } from "../_shared/ibis-opportunity-scanner.ts";

const ALLOWED = new Set(["https://ftnplatform.org", "https://www.ftnplatform.org", "http://localhost:3000", "http://127.0.0.1:3000"]);
function originAllowed(value: string | null) { if (!value) return true; if (ALLOWED.has(value)) return true; try { const u = new URL(value); return u.protocol === "https:" && /^(?:[a-z0-9-]+\.)?ftn-platform-website\.pages\.dev$/i.test(u.hostname); } catch { return false; } }
function cors(origin: string | null) { return { "access-control-allow-origin": origin && originAllowed(origin) ? origin : "https://ftnplatform.org", "access-control-allow-methods": "POST,OPTIONS", "access-control-allow-headers": "apikey,authorization,content-type", "content-type": "application/json; charset=utf-8", "cache-control": "no-store", "vary": "Origin" }; }
function reply(origin: string | null, body: unknown, status = 200) { return new Response(JSON.stringify(body), { status, headers: cors(origin) }); }
function validKey(req: Request) { const supplied = req.headers.get("apikey") || ""; try { return !!supplied && Object.values(JSON.parse(Deno.env.get("SUPABASE_PUBLISHABLE_KEYS") || "{}")).includes(supplied); } catch { return false; } }
function decodeHtml(s: string) { return s.replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,"$1").replace(/&amp;/g,"&").replace(/&quot;/g,'"').replace(/&#x27;|&#39;/g,"'").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim(); }
function cleanAnswer(s:string){return String(s||"").split(/\n+/).map(x=>x.trim()).filter(Boolean).map(line=>line.replace(/^(?:CLASS|EVIDENCE BOUNDARY|USEFUL CONCLUSION|WHAT COULD CHANGE IT|NEXT ACTION|CONSEQUENCES FOR MONEY, RISK, TIME, CONTROL, OWNERSHIP, DATA, FEASIBILITY, AND OPTIONALITY)\s*:\s*/i,"")).filter(line=>line&&!/^Request class\s*:/i.test(line)).join("\n\n").trim();}
function normalizedSubject(q:string){let s=String(q||"").trim().replace(/[?!.,]+$/g,"");const patterns=[/^(?:please\s+)?tell me about\s+/i,/^(?:please\s+)?who (?:is|was)\s+/i,/^(?:please\s+)?what do you know about\s+/i,/^(?:please\s+)?give me (?:information|info) (?:about|on)\s+/i,/^(?:please\s+)?look up\s+/i,/^(?:please\s+)?search (?:the )?web for\s+/i,/^(?:please\s+)?google\s+/i,/^(?:please\s+)?research\s+/i];for(const p of patterns)s=s.replace(p,"");return s.trim()||q.trim();}
function searchQueries(q:string){const subject=normalizedSubject(q);const person=/^[\p{L}'’-]+(?:\s+[\p{L}'’-]+){1,5}$/u.test(subject)&&!/\b(news|weather|price|rate|law|election|today|latest)\b/i.test(subject);if(person)return [`"${subject}"`,`"${subject}" Trinidad Tobago`,`"${subject}" Caribbean`];const news=/\b(news|today|latest|current|right now|recent)\b/i.test(q);return Array.from(new Set([subject,news?subject.replace(/^(?:what(?:'s| is)?|tell me|show me)\s+/i,""):subject,q])).filter(Boolean).slice(0,3);}
function requiredTerms(q:string){const s=normalizedSubject(q);if(/^[\p{L}'’-]+(?:\s+[\p{L}'’-]+){1,5}$/u.test(s))return s.toLowerCase().split(/\s+/).filter(w=>w.length>1);return [] as string[];}
function relevantResult(x:{title:string;snippet:string;text?:string},terms:string[]){if(!terms.length)return true;const hay=`${x.title} ${x.snippet} ${x.text||""}`.toLowerCase();return terms.every(t=>hay.includes(t));}
function sourceClassFor(uri: string, title: string): CebosSourceClass { let host = ""; try { host = new URL(uri).hostname.toLowerCase(); } catch {} const text = `${host} ${title}`.toLowerCase(); if (/\.gov\.|\.gov$|gov\.tt$|ttparliament\.org|caricom\.org|caribank\.org/.test(host)) return "OFFICIAL_GOVERNMENT"; if (/court|judiciary|legislation|gazette|laws?\b/.test(text)) return "LEGISLATION_PUBLIC_RECORD"; if (/\.edu\.|\.ac\.|university|journal|doi\.org/.test(text)) return "ACADEMIC"; if (/newsday|guardian\.co\.tt|trinidadexpress|loopnews|reuters|apnews|bbc|cnn|nytimes|washingtonpost|jamaicaobserver|jamaica-gleaner|film festival|ttfilmfestival|wevibes/.test(text)) return "REPUTABLE_JOURNALISM"; if (/imdb\.com|linkedin|company|official/.test(text)) return "CORPORATE_STATEMENT"; if (/facebook|instagram|x\.com|twitter|tiktok|youtube/.test(host)) return "CREATOR_SOCIAL"; if (/reddit|forum|community/.test(text)) return "COMMUNITY_DISCUSSION"; return "UNKNOWN"; }
function evidenceStatusFor(sourceClass: CebosSourceClass): CebosEvidenceStatus { if (sourceClass === "OFFICIAL_GOVERNMENT" || sourceClass === "LEGISLATION_PUBLIC_RECORD" || sourceClass === "PRIMARY_EVIDENCE") return "VERIFIED"; if (sourceClass === "ACADEMIC" || sourceClass === "REPUTABLE_JOURNALISM") return "CORROBORATED"; if (sourceClass === "CORPORATE_STATEMENT") return "WORKING_INFERENCE"; return "SPECULATIVE_LEAD"; }
function resolveDdg(raw: string) { try { const u = new URL(raw.startsWith("//") ? `https:${raw}` : raw, "https://html.duckduckgo.com"); const target = u.searchParams.get("uddg"); return target ? decodeURIComponent(target) : u.href; } catch { return raw; } }
async function searxSearch(query:string){try{const base="https://search.inetol.net";const r=await fetch(`${base}/search?q=${encodeURIComponent(query)}`,{headers:{"user-agent":"Mozilla/5.0 (compatible; FTN-IBIS-Research/1.0)","accept":"text/html"},signal:AbortSignal.timeout(12000)});if(!r.ok)return[] as Array<{title:string;url:string;snippet:string}>;const html=await r.text(),articles=html.match(/<article\b[\s\S]*?<\/article>/gi)||[],out:Array<{title:string;url:string;snippet:string}>=[];for(const article of articles.slice(0,15)){const h=article.match(/<h3[^>]*>[\s\S]*?<a[^>]+href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>[\s\S]*?<\/h3>/i)||article.match(/<a[^>]+href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/i);if(!h)continue;let url=decodeHtml(h[1]);try{url=new URL(url,base).href}catch{}if(!/^https?:\/\//i.test(url)||url.startsWith(base))continue;const sn=article.match(/<p[^>]+class=["'][^"']*(?:content|result-content)[^"']*["'][^>]*>([\s\S]*?)<\/p>/i)||article.match(/<p[^>]*>([\s\S]*?)<\/p>/i);out.push({title:decodeHtml(h[2]),url,snippet:decodeHtml(sn?.[1]||"")});}return out}catch{return[] as Array<{title:string;url:string;snippet:string}>}}
async function bingSearch(query:string){try{const r=await fetch(`https://www.bing.com/search?q=${encodeURIComponent(query)}&format=rss`,{headers:{"user-agent":"Mozilla/5.0 (compatible; FTN-IBIS-Research/1.0)","accept":"application/rss+xml,application/xml,text/xml"},signal:AbortSignal.timeout(12000)});if(!r.ok)return[] as Array<{title:string;url:string;snippet:string}>;const xml=await r.text(),items=xml.match(/<item>[\s\S]*?<\/item>/gi)||[],out:Array<{title:string;url:string;snippet:string}>=[];for(const item of items.slice(0,10)){const title=decodeHtml(item.match(/<title>([\s\S]*?)<\/title>/i)?.[1]||""),url=decodeHtml(item.match(/<link>([\s\S]*?)<\/link>/i)?.[1]||""),snippet=decodeHtml(item.match(/<description>([\s\S]*?)<\/description>/i)?.[1]||"");if(title&&/^https?:\/\//i.test(url))out.push({title,url,snippet})}return out}catch{return[] as Array<{title:string;url:string;snippet:string}>}}
async function ddgSearch(query:string){try{const r=await fetch(`https://html.duckduckgo.com/html/?q=${encodeURIComponent(query)}`,{headers:{"user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/152 Safari/537.36","accept":"text/html"},signal:AbortSignal.timeout(12000)});if(!r.ok)return[] as Array<{title:string;url:string;snippet:string}>;const html=await r.text(),blocks=html.match(/<div[^>]+class="[^"]*result[^"]*results_links[^"]*"[\s\S]*?(?=<div[^>]+class="[^"]*result[^"]*results_links|<div id="links"|$)/gi)||[],out:Array<{title:string;url:string;snippet:string}>=[];for(const b of blocks.slice(0,10)){const a=b.match(/<a[^>]+class="[^"]*result__a[^"]*"[^>]+href="([^"]+)"[^>]*>([\s\S]*?)<\/a>/i);if(!a)continue;const sn=b.match(/class="[^"]*result__snippet[^"]*"[^>]*>([\s\S]*?)<\/a>/i)||b.match(/class="[^"]*result__snippet[^"]*"[^>]*>([\s\S]*?)<\/div>/i),target=resolveDdg(decodeHtml(a[1]));if(/^https?:\/\//i.test(target))out.push({title:decodeHtml(a[2]),url:target,snippet:decodeHtml(sn?.[1]||"")})}return out}catch{return[] as Array<{title:string;url:string;snippet:string}>}}
async function pageText(url:string){try{const r=await fetch(url,{headers:{"user-agent":"Mozilla/5.0 (compatible; FTN-IBIS-Research/1.0)"},redirect:"follow",signal:AbortSignal.timeout(6500)});if(!r.ok)return"";const type=r.headers.get("content-type")||"";if(!/text\/(html|plain)/i.test(type))return"";const html=(await r.text()).slice(0,220000);return decodeHtml(html.replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ")).slice(0,4500)}catch{return""}}
function evidencePacket(items:Array<{title:string;url:string;snippet:string;text?:string}>){return items.slice(0,7).map((x,i)=>`[${i+1}] ${x.title}\nURL: ${x.url}\n${x.snippet}${x.text?`\nPage text: ${x.text}`:""}`).join("\n\n")}
async function synthesizeGemini(key:string,model:string,query:string,directive:string,items:Array<{title:string;url:string;snippet:string;text?:string}>){try{const prompt=`${directive}\nWrite a natural research answer in the style of a strong search assistant: direct answer first, then the most useful supporting context, caveats only where material, and a practical next step only if it genuinely helps. Use only the evidence packet. Cite [1], [2], etc. Do NOT output internal labels such as CLASS, EVIDENCE BOUNDARY, USEFUL CONCLUSION, WHAT COULD CHANGE IT, NEXT ACTION, CEBOS, EBR, or generic money/risk/control checklists. Never invent unsupported facts.\n\nQUESTION: ${query}\n\nEVIDENCE:\n${evidencePacket(items)}`;const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent`,{method:"POST",headers:{"content-type":"application/json","x-goog-api-key":key},body:JSON.stringify({contents:[{role:"user",parts:[{text:prompt}]}],generationConfig:{temperature:0.15,maxOutputTokens:1800}}),signal:AbortSignal.timeout(30000)}),data=await r.json().catch(()=>({}));if(!r.ok)return"";return cleanAnswer((data?.candidates?.[0]?.content?.parts||[]).map((p:any)=>p?.text||"").join(""))}catch{return""}}
async function synthesizeCloudflare(query:string,directive:string,items:Array<{title:string;url:string;snippet:string;text?:string}>){try{const account=Deno.env.get("CLOUDFLARE_ACCOUNT_ID")||"",token=Deno.env.get("CLOUDFLARE_API_TOKEN")||"",model="@cf/meta/llama-3.1-8b-instruct";if(!account||!token)return"";const prompt=`${directive}\nWrite a natural evidence-backed answer. Direct answer first; then useful context. Cite [1], [2], etc. Use only the evidence packet. Do not expose CLASS, EVIDENCE BOUNDARY, USEFUL CONCLUSION, WHAT COULD CHANGE IT, NEXT ACTION, CEBOS, EBR, or generic framework/checklist headings. Never invent unsupported facts.\n\nQUESTION: ${query}\n\nEVIDENCE:\n${evidencePacket(items)}`;const r=await fetch(`https://api.cloudflare.com/client/v4/accounts/${account}/ai/run/${model}`,{method:"POST",headers:{"content-type":"application/json","authorization":`Bearer ${token}`},body:JSON.stringify({messages:[{role:"user",content:prompt}],temperature:0.15}),signal:AbortSignal.timeout(22000)}),data=await r.json().catch(()=>({}));if(!r.ok||data?.success===false)return"";return cleanAnswer(typeof data?.result?.response==="string"?data.result.response:"")}catch{return""}}

Deno.serve(async (req) => {
  const origin=req.headers.get("origin"); if(req.method==="OPTIONS")return new Response(null,{status:originAllowed(origin)?204:403,headers:cors(origin)}); if(req.method!=="POST")return reply(origin,{error:"POST required"},405); if(!originAllowed(origin))return reply(origin,{error:"Origin not allowed"},403); if(!validKey(req))return reply(origin,{error:"Invalid FTN client key"},401);
  let payload:{query?:unknown;locationContext?:unknown;action?:unknown};try{payload=await req.json()}catch{return reply(origin,{error:"Invalid request"},400)}
  const query=typeof payload.query==="string"?payload.query.trim().slice(0,2000):"",locationContext=typeof payload.locationContext==="string"?payload.locationContext.trim().slice(0,200):null,key=Deno.env.get("GEMINI_API_KEY")||"",model=Deno.env.get("IBIS_WEB_RESEARCH_MODEL")||Deno.env.get("GEMINI_MODEL")||"gemini-2.5-flash";
  if(payload.action==="health")return reply(origin,{capability:"WEB_RESEARCH",provider:"Google Search grounding + SearXNG + Bing RSS + DuckDuckGo + Gemini/Cloudflare synthesis",model,configured:!!(key||Deno.env.get("CLOUDFLARE_API_TOKEN")),ready:!!(key||Deno.env.get("CLOUDFLARE_API_TOKEN")),cebos:true,opportunityScanner:true,inferenceAttempted:false,checkedAt:new Date().toISOString()});if(!query)return reply(origin,{error:"query required"},400);if(!key&&!Deno.env.get("CLOUDFLARE_API_TOKEN"))return reply(origin,{error:"No web-research reasoning provider is configured."},503);
  const state=createReasoningState({request:query,locationContext});scanOpportunitySignals(state);const directive=providerReasoningDirective(state),queries=searchQueries(query),terms=requiredTerms(query),searchInstruction=[directive,"Search the broad public web for the actual subject of the question, not the conversational wrapper. Seek confirming and contradicting evidence. For Caribbean subjects include local sources and official records. Do not infer absence from poor indexing. Return a natural, complete answer. Never expose internal CEBOS/EBR labels or generic framework headings."].join(" ");let answer="",provider="Google Search grounding via Gemini",providerStatus:number|null=null,providerCode:string|null=null;
  if(key){try{const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent`,{method:"POST",headers:{"content-type":"application/json","x-goog-api-key":key},body:JSON.stringify({systemInstruction:{parts:[{text:searchInstruction}]},contents:[{role:"user",parts:[{text:query}]}],tools:[{google_search:{}}],generationConfig:{temperature:0.15,maxOutputTokens:1800}}),signal:AbortSignal.timeout(30000)}),data=await r.json().catch(()=>({}));providerStatus=r.status;providerCode=data?.error?.status||null;if(r.ok){const c=data?.candidates?.[0]||{};answer=cleanAnswer((c?.content?.parts||[]).map((p:any)=>p?.text||"").join(""));const chunks=Array.isArray(c?.groundingMetadata?.groundingChunks)?c.groundingMetadata.groundingChunks:[],seen=new Set<string>();for(let i=0;i<chunks.length;i++){const w=chunks[i]?.web,uri=typeof w?.uri==="string"?w.uri:"",title=typeof w?.title==="string"?w.title:uri;if(!uri||seen.has(uri))continue;seen.add(uri);const sc=sourceClassFor(uri,title),scores=sourceScores(sc);addEvidence(state,{id:`google-${i}`,claim:title,status:evidenceStatusFor(sc),sourceClass:sc,sourceUrl:uri,publisher:title,retrievedAt:new Date().toISOString(),discoveryUtility:scores.discoveryUtility,decisionAuthority:scores.decisionAuthority,geographicRelevance:state.caribbeanRelevant?"Caribbean context requested or inferred":null,contradictions:[]})}}}catch{}}
  if(!answer||!state.evidence.length){let found:Array<{title:string;url:string;snippet:string}>=[];const seen=new Set<string>();for(const sq of queries){let batch=await searxSearch(sq);if(!batch.length)batch=await bingSearch(sq);if(!batch.length)batch=await ddgSearch(sq);for(const x of batch){if(seen.has(x.url))continue;seen.add(x.url);found.push(x)}if(found.length>=12)break}const enriched=(await Promise.all(found.slice(0,12).map(async x=>({...x,text:await pageText(x.url)})))).filter(x=>relevantResult(x,terms)).slice(0,7);for(let i=0;i<enriched.length;i++){const x=enriched[i],sc=sourceClassFor(x.url,x.title),scores=sourceScores(sc);addEvidence(state,{id:`web-${i}`,claim:x.title,status:evidenceStatusFor(sc),sourceClass:sc,sourceUrl:x.url,publisher:(()=>{try{return new URL(x.url).hostname.replace(/^www\./,"")}catch{return x.title}})(),retrievedAt:new Date().toISOString(),discoveryUtility:scores.discoveryUtility,decisionAuthority:scores.decisionAuthority,geographicRelevance:state.caribbeanRelevant?"Caribbean context requested or inferred":null,contradictions:[]})}if(enriched.length){answer=key?await synthesizeGemini(key,model,query,directive,enriched):"";if(!answer)answer=await synthesizeCloudflare(query,directive,enriched);provider=answer?"Independent web search + evidence synthesis":"Independent web search"}}
  const compact={version:state.version,requestClass:state.requestClass,caribbeanRelevant:state.caribbeanRelevant,sourcePlan:researchSourcePlan(state).slice(0,6),evidence:evidenceSummary(state),opportunitySignals:state.opportunitySignals,searchQueries:queries},sources=state.evidence.map(e=>({title:e.claim,url:e.sourceUrl,publisher:e.publisher,sourceClass:e.sourceClass,evidenceStatus:e.status,discoveryUtility:e.discoveryUtility,decisionAuthority:e.decisionAuthority}));if(!answer||!state.evidence.length)return reply(origin,{error:"Web research completed without enough relevant evidence to answer.",providerStatus,providerCode,sources,cebos:compact},424);return reply(origin,{answer:cleanAnswer(answer),sources,provider,model,retrievedAt:new Date().toISOString(),providerStatus,providerCode,cebos:compact});
});
