import { chromium } from 'playwright';
import assert from 'node:assert/strict';
const BASE=process.env.FTN_TEST_BASE||'http://127.0.0.1:3000';
const browser=await chromium.launch({headless:true});
async function scenario(name,fn,viewport={width:1280,height:900}){const context=await browser.newContext({viewport});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));try{await fn(page);assert.equal(errors.length,0,errors.join('\n'));console.log('FOUNDATION PASS',name);}finally{await context.close();}}
async function open(page,path){const r=await page.goto(BASE+path,{waitUntil:'domcontentloaded',timeout:30000});assert(r&&r.ok(),`${path} returned ${r?.status()}`);await page.waitForTimeout(150);const overflow=await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth);assert(overflow<=3,`${path} horizontal overflow ${overflow}px`);}
async function guestAuth(page){await page.route('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@*/dist/umd/supabase.min.js',route=>route.fulfill({status:200,contentType:'application/javascript',body:`window.supabase={createClient:function(){return{auth:{getUser:async()=>({data:{user:null},error:null}),getSession:async()=>({data:{session:null},error:null}),onAuthStateChange:function(){return{data:{subscription:{unsubscribe:function(){}}}}},signOut:async()=>({error:null})},functions:{invoke:async()=>({data:null,error:new Error('Denied in guest test')})}}}};`}));}

await scenario('registry-driven-home',async page=>{await open(page,'/');await page.waitForSelector('#find-your-path');assert.equal(await page.locator('.country-switcher-dialog.is-open').count(),0);await page.locator('[data-ftn-discovery-trigger]').first().click();await page.fill('#ftn-discovery-query','parliament bill');await page.waitForSelector('.ftn-discovery__result[href="/parliament/"]');assert.match(await page.locator('h1').innerText(),/Caribbean.*Operating System/is);});
await scenario('mobile-home-no-force',async page=>{await open(page,'/');await page.waitForSelector('#find-your-path');assert.equal(await page.locator('.country-switcher-dialog.is-open').count(),0);},{width:390,height:844});
await scenario('public-product-directory',async page=>{await open(page,'/applications/');await page.waitForSelector('.ftn-registry-directory');assert(await page.locator('.ftn-registry-card').count()>=18);assert.equal(await page.locator('.ftn-registry-card[href="/love/"],.ftn-registry-card[href="/health/"]').count(),0);assert.equal(await page.locator('.ftn-registry-card[href="/govern/"]').count(),1);});
await scenario('parliament-sources',async page=>{await open(page,'/parliament/');assert.equal(await page.locator('.parl-source-card').count(),27);assert.equal(await page.locator('#parliament-country').inputValue(),'tt');assert.match(await page.locator('#parliament-watch').innerText(),/Trinidad and Tobago|Public Administration/i);await page.selectOption('#parliament-country','bb');assert.match(await page.locator('#parliament-watch').innerText(),/Barbados|Senate/i);});
await scenario('invest-watchlist',async page=>{await open(page,'/invest/');assert.equal(await page.locator('#invest-sources .nexus-card').count(),4);await page.locator('[data-watch]').first().click();assert.match(await page.locator('#invest-watchlist').innerText(),/Ministry|Central Bank|Stock Exchange|Securities/i);});
await scenario('health-is-vaulted-not-intake',async page=>{await open(page,'/health/');assert.match(await page.locator('main').innerText(),/not publicly available|no FTN health service is open/i);assert.equal(await page.locator('meta[name="robots"]').getAttribute('content'),'noindex,follow');assert.equal(await page.locator('main input,main textarea,main select').count(),0);});
await scenario('account-guest-and-private-denial',async page=>{await guestAuth(page);await open(page,'/account/');await page.waitForSelector('#account-email-form');assert.match(await page.locator('#account-state').innerText(),/Guest/);});
await scenario('love-is-vaulted-without-private-runtime',async page=>{await open(page,'/love/');assert.match(await page.locator('main').innerText(),/not publicly available|service is not open/i);assert.equal(await page.locator('meta[name="robots"]').getAttribute('content'),'noindex,follow');assert.equal(await page.locator('#love-private-root').count(),0);});
await scenario('god-mode-fails-closed-for-guest',async page=>{await guestAuth(page);await open(page,'/god-mode/');await page.waitForTimeout(200);assert.equal(await page.locator('[data-emergency]').count(),0);assert.match(await page.locator('#god-mode-root').innerText(),/Authorization required/);});
await scenario('contact-protected-transaction',async page=>{await page.route('**/config/public-runtime.json',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({schemaVersion:1,turnstileSiteKey:'1x00000000000000000000AA'})}));await page.route('https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit',route=>route.fulfill({status:200,contentType:'application/javascript',body:`window.turnstile={render:function(m,o){setTimeout(function(){o.callback('FTN_TEST_TOKEN')},0)}};`}));await page.route('https://jshmidfpqrajxtukzges.supabase.co/functions/v1/ftn-transactions',route=>route.fulfill({status:201,contentType:'application/json',body:JSON.stringify({ok:true,transaction_id:'FTN-TEST-CONTACT'})}));await open(page,'/contact/');await page.waitForFunction(()=>document.querySelector('#contact-form-el [name="cf-turnstile-response"]')?.value==='FTN_TEST_TOKEN');await page.fill('#cf-name','FTN Release Test');await page.fill('#cf-email','release@example.com');await page.selectOption('#cf-category','general');await page.fill('#cf-message','Testing the protected contact transaction path.');await page.check('[name="authority"]');await page.locator('#contact-form-el').evaluate(f=>f.requestSubmit());await page.waitForFunction(()=>/FTN-TEST-CONTACT/.test(document.querySelector('#contact-form-status')?.textContent||''));});
await scenario('pwa-private-exclusions',async page=>{await open(page,'/');const [manifest,sw]=await page.evaluate(()=>Promise.all([fetch('/manifest.webmanifest').then(r=>r.text()),fetch('/service-worker.js').then(r=>r.text())]));assert(!manifest.includes('god-mode'));assert(!manifest.includes('/love/'));assert(!manifest.includes('/health/'));for(const route of ['god-mode','mission-control','account','love','health','ibis-ai'])assert(sw.includes(route),`private or vaulted route missing from service worker exclusion: ${route}`);});

await browser.close();console.log('11/11 FTN shared-foundation release scenarios passed.');
