import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const allowed=new Set(["https://ftnplatform.org","https://www.ftnplatform.org",...(Deno.env.get("FTN_ALLOWED_ORIGINS")||"").split(",").map(x=>x.trim()).filter(Boolean)]);
const windows=new Map<string,{count:number;reset:number}>();
function h(origin:string|null){return{"content-type":"application/json; charset=utf-8","access-control-allow-origin":origin&&allowed.has(origin)?origin:"https://ftnplatform.org","access-control-allow-headers":"authorization,apikey,content-type","access-control-allow-methods":"POST,OPTIONS","cache-control":"no-store","vary":"Origin"};}
function out(origin:string|null,body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:h(origin)});}
function text(v:unknown,max=1000){return typeof v==="string"?v.trim().slice(0,max):"";}
function limited(id:string){const now=Date.now(),w=windows.get(id);if(!w||w.reset<now){windows.set(id,{count:1,reset:now+60_000});return false;}w.count++;return w.count>40;}
function adult(date:string){const birth=new Date(date+"T00:00:00Z");if(!Number.isFinite(birth.getTime()))return false;const now=new Date(),cutoff=new Date(Date.UTC(now.getUTCFullYear()-18,now.getUTCMonth(),now.getUTCDate()));return birth<=cutoff;}
Deno.serve(async(req)=>{const origin=req.headers.get("origin");if(req.method==="OPTIONS")return new Response(null,{status:204,headers:h(origin)});if(req.method!=="POST"||(origin&&!allowed.has(origin)))return out(origin,{error:"Not allowed"},403);const token=req.headers.get("authorization")?.replace(/^Bearer\s+/i,"")||"",admin=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,{auth:{persistSession:false,autoRefreshToken:false}});const {data,error}=await admin.auth.getUser(token),user=data?.user;if(error||!user)return out(origin,{error:"Authenticate first"},401);if(limited(user.id))return out(origin,{error:"Too many FTN Love actions. Wait one minute."},429);let body:any={};try{body=await req.json();}catch{return out(origin,{error:"Invalid request"},400);}const action=text(body.action,50);
  if(action==="profile"){const {data:profile}=await admin.from("ftn_love_profiles").select("display_name,birth_date,country_code,bio,preferences,consent_version,consented_at,discovery_enabled,status,updated_at").eq("user_id",user.id).maybeSingle();return out(origin,{profile:profile||null});}
  if(action==="profile-upsert"){const display=text(body.displayName,80),birth=text(body.birthDate,10),country=text(body.countryCode,2).toUpperCase(),bio=text(body.bio,1000);if(display.length<2||!adult(birth)||!/^[A-Z]{2}$/.test(country)||body.consent!==true)return out(origin,{error:"Adult age, consent, display name and two-letter country are required"},422);const record={user_id:user.id,display_name:display,birth_date:birth,country_code:country,bio,preferences:body.preferences&&typeof body.preferences==="object"?body.preferences:{},consent_version:"2026-08-10",consented_at:new Date().toISOString(),discovery_enabled:body.discoveryEnabled===true,status:"ACTIVE",updated_at:new Date().toISOString()};const {error:saveError}=await admin.from("ftn_love_profiles").upsert(record,{onConflict:"user_id"});if(saveError)return out(origin,{error:"Profile was not saved"},500);return out(origin,{ok:true,profile:{display_name:display,country_code:country,bio,discovery_enabled:record.discovery_enabled,status:"ACTIVE"}});}
  const {data:own}=await admin.from("ftn_love_profiles").select("user_id,country_code,discovery_enabled,status").eq("user_id",user.id).maybeSingle();if(!own||own.status!=="ACTIVE")return out(origin,{error:"Complete an active FTN Love profile first"},409);
  if(action==="discover"){if(!own.discovery_enabled)return out(origin,{profiles:[],notice:"Enable controlled discovery in your profile first."});const {data:blocks}=await admin.from("ftn_love_blocks").select("blocker_id,blocked_id").or(`blocker_id.eq.${user.id},blocked_id.eq.${user.id}`),excluded=new Set([user.id]);(blocks||[]).forEach((b:any)=>{excluded.add(b.blocker_id);excluded.add(b.blocked_id);});const {data:profiles}=await admin.from("ftn_love_profiles").select("user_id,display_name,country_code,bio,preferences,updated_at").eq("status","ACTIVE").eq("discovery_enabled",true).eq("country_code",own.country_code).limit(20);return out(origin,{profiles:(profiles||[]).filter((p:any)=>!excluded.has(p.user_id)).map((p:any)=>({profileId:p.user_id,displayName:p.display_name,countryCode:p.country_code,bio:p.bio,preferences:p.preferences,updatedAt:p.updated_at}))});}
  if(action==="interest"){const target=text(body.profileId,40);if(!/^[0-9a-f-]{36}$/i.test(target)||target===user.id)return out(origin,{error:"Invalid profile"},422);const {data:targetProfile}=await admin.from("ftn_love_profiles").select("user_id,status,discovery_enabled").eq("user_id",target).maybeSingle();if(!targetProfile||targetProfile.status!=="ACTIVE"||!targetProfile.discovery_enabled)return out(origin,{error:"That profile is not available"},404);const {data:block}=await admin.from("ftn_love_blocks").select("blocker_id").or(`and(blocker_id.eq.${user.id},blocked_id.eq.${target}),and(blocker_id.eq.${target},blocked_id.eq.${user.id})`).limit(1).maybeSingle();if(block)return out(origin,{error:"This connection is unavailable"},403);await admin.from("ftn_love_interests").upsert({sender_id:user.id,target_id:target,status:"PENDING",updated_at:new Date().toISOString()},{onConflict:"sender_id,target_id"});const {data:reverse}=await admin.from("ftn_love_interests").select("status").eq("sender_id",target).eq("target_id",user.id).in("status",["PENDING","MATCHED"]).maybeSingle();if(!reverse)return out(origin,{ok:true,matched:false,status:"Interest recorded privately"});const pair=[user.id,target].sort(),{data:match,error:matchError}=await admin.from("ftn_love_matches").upsert({user_a:pair[0],user_b:pair[1],status:"ACTIVE"},{onConflict:"user_a,user_b"}).select("id").single();if(matchError)return out(origin,{error:"Mutual interest found but match could not be created"},500);await admin.from("ftn_love_interests").update({status:"MATCHED",updated_at:new Date().toISOString()}).or(`and(sender_id.eq.${user.id},target_id.eq.${target}),and(sender_id.eq.${target},target_id.eq.${user.id})`);return out(origin,{ok:true,matched:true,matchId:match.id,status:"Mutual match created"});}
  if(action==="matches"){const {data:matches}=await admin.from("ftn_love_matches").select("id,user_a,user_b,status,created_at").or(`user_a.eq.${user.id},user_b.eq.${user.id}`).eq("status","ACTIVE").order("created_at",{ascending:false}),ids=(matches||[]).map((m:any)=>m.user_a===user.id?m.user_b:m.user_a),{data:profiles}=ids.length?await admin.from("ftn_love_profiles").select("user_id,display_name,country_code,bio").in("user_id",ids):{data:[] as any[]},map=new Map((profiles||[]).map((p:any)=>[p.user_id,p]));return out(origin,{matches:(matches||[]).map((m:any)=>({matchId:m.id,createdAt:m.created_at,profile:map.get(m.user_a===user.id?m.user_b:m.user_a)||null}))});}
  if(action==="messages"){const matchId=text(body.matchId,40),{data:match}=await admin.from("ftn_love_matches").select("id,user_a,user_b,status").eq("id",matchId).maybeSingle();if(!match||![match.user_a,match.user_b].includes(user.id))return out(origin,{error:"Match not found"},404);if(match.status!=="ACTIVE")return out(origin,{error:"Messaging is closed"},409);if(text(body.message,2000)){const message=text(body.message,2000),{error:sendError}=await admin.from("ftn_love_messages").insert({match_id:matchId,sender_id:user.id,body:message});if(sendError)return out(origin,{error:"Message was not sent"},500);}const {data:messages}=await admin.from("ftn_love_messages").select("id,sender_id,body,created_at").eq("match_id",matchId).is("deleted_at",null).order("created_at").limit(100);return out(origin,{messages:(messages||[]).map((m:any)=>({id:m.id,mine:m.sender_id===user.id,body:m.body,createdAt:m.created_at}))});}
  if(action==="block"){const target=text(body.profileId,40);if(!/^[0-9a-f-]{36}$/i.test(target)||target===user.id)return out(origin,{error:"Invalid profile"},422);const {error:blockError}=await admin.from("ftn_love_blocks").upsert({blocker_id:user.id,blocked_id:target},{onConflict:"blocker_id,blocked_id"});if(blockError)return out(origin,{error:"Block was not recorded"},500);const pairFilter=`and(sender_id.eq.${user.id},target_id.eq.${target}),and(sender_id.eq.${target},target_id.eq.${user.id})`;const [{error:interestError},{error:matchError}]=await Promise.all([admin.from("ftn_love_interests").delete().or(pairFilter),admin.from("ftn_love_matches").update({status:"BLOCKED"}).or(`and(user_a.eq.${user.id},user_b.eq.${target}),and(user_a.eq.${target},user_b.eq.${user.id})`)]);if(interestError||matchError)return out(origin,{error:"Block was recorded but relationship containment needs review"},500);return out(origin,{ok:true,status:"Blocked"});}
  if(action==="report"){const target=text(body.profileId,40),code=text(body.reasonCode,80),detail=text(body.detail,2000);if(!/^[0-9a-f-]{36}$/i.test(target)||target===user.id||!code)return out(origin,{error:"Profile and reason are required"},422);const {data:report,error:reportError}=await admin.from("ftn_love_reports").insert({reporter_id:user.id,reported_id:target,reason_code:code,detail}).select("id,status").single();if(reportError)return out(origin,{error:"Report was not recorded"},500);return out(origin,{ok:true,report});}
  if(action==="delete-profile"){if(body.confirm!=="DELETE LOVE")return out(origin,{error:"Exact deletion confirmation required"},422);const [{data:matches,error:matchesError},{error:interestError},{error:blockError}]=await Promise.all([admin.from("ftn_love_matches").select("id").or(`user_a.eq.${user.id},user_b.eq.${user.id}`),admin.from("ftn_love_interests").delete().or(`sender_id.eq.${user.id},target_id.eq.${user.id}`),admin.from("ftn_love_blocks").delete().or(`blocker_id.eq.${user.id},blocked_id.eq.${user.id}`)]);if(matchesError||interestError||blockError)return out(origin,{error:"Love relationship data could not be deleted safely"},500);const matchIds=(matches||[]).map((m:any)=>m.id);if(matchIds.length){const {error:matchDeleteError}=await admin.from("ftn_love_matches").delete().in("id",matchIds);if(matchDeleteError)return out(origin,{error:"Love messages could not be deleted safely"},500);}const {error:deleteError}=await admin.from("ftn_love_profiles").delete().eq("user_id",user.id);if(deleteError)return out(origin,{error:"Love profile was not deleted"},500);return out(origin,{ok:true,status:"FTN Love profile, interests, blocks, matches and messages deleted; safety reports may be retained as evidence."});}
  return out(origin,{error:"Unknown FTN Love action"},400);
});
