// FTN Platform — footer synchronization script.
//
// Phase 3 footer consolidation (see GOVERNANCE/FTN_Repair_Ledger_2026-08-24.md). Canonical content
// lives in data/footer-config.mjs; this script writes it into every configured page inside a
// generated-region marker pair, so hand edits inside the markers get silently overwritten (that's
// the point -- edit the config, not the HTML) while everything outside the markers is left alone.
//
// Two variants, not one -- see data/footer-config.mjs's own header comment for why the site
// genuinely has two different footer purposes, not accidental drift to force into one shape:
//   'full'        -- the entire <footer class="site-footer">...</footer> is generated.
//   'bottom-only' -- only the <div class="site-footer__bottom">...</div> is generated; hand-curated
//                    content columns above it (product-specific navigation) are left untouched.
//
// Run: node scripts/sync-footer.mjs           -- writes every configured page.
// Run: node scripts/sync-footer.mjs --check   -- reports drift, exits 1 if any page would change.
// Run: node scripts/sync-footer.mjs --group=full        -- only the 'full' variant pages.
// Run: node scripts/sync-footer.mjs --group=bottom-only -- only the 'bottom-only' variant pages.
// (Group flags compose with --check.)

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { dirname, resolve } from 'node:path';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const { BRAND, BOTTOM_LINKS, FULL_COLUMNS, PAGES } = await import(pathToFileURL(resolve(root, 'data/footer-config.mjs')));

const MARK_START = '<!-- FTN:FOOTER:START (generated by scripts/sync-footer.mjs -- do not hand-edit this region, edit data/footer-config.mjs instead) -->';
const MARK_END = '<!-- FTN:FOOTER:END -->';

function esc(v) {
  return String(v == null ? '' : v).replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
}

function loadRegistry() {
  const fakeWindow = {};
  const dataSrc = readFileSync(resolve(root, 'js/product-registry-data.js'), 'utf8');
  const apiSrc = readFileSync(resolve(root, 'js/product-registry.js'), 'utf8');
  const fn = new Function('window', dataSrc + '\n' + apiSrc);
  fn(fakeWindow);
  return fakeWindow.FTN.ProductRegistry;
}

function resolveLink(entry, Registry) {
  if (entry.registry) {
    const product = Registry.get(entry.registry);
    if (!product) throw new Error(`footer-config references unknown registry id: ${entry.registry}`);
    return { label: product.name, href: product.route };
  }
  return entry;
}

function bottomBarHtml(Registry) {
  const links = BOTTOM_LINKS.map((l) => resolveLink(l, Registry));
  return (
    '<div class="site-footer__bottom">' +
      `<p>${esc(BRAND.copyright)}</p>` +
      '<div class="site-footer__bottom-links">' +
        links.map((l) => `<a href="${esc(l.href)}">${esc(l.label)}</a>`).join('') +
      '</div>' +
    '</div>'
  );
}

function brandBlockHtml() {
  return (
    '<div class="site-footer__brand">' +
      '<svg viewBox="0 0 220 64" role="img" class="logo-mark--footer">' +
        '<text x="0" y="40" font-family="Montserrat,Arial,sans-serif" font-weight="800" font-size="40" fill="#fff">F<tspan class="logo-mark__t">T</tspan>N</text>' +
        '<text x="2" y="57" font-family="Montserrat,Arial,sans-serif" font-weight="600" font-size="11" letter-spacing="4" fill="#fff">PLATFORM</text>' +
      '</svg>' +
      `<p class="site-footer__tagline">${esc(BRAND.tagline)}</p>` +
    '</div>'
  );
}

function columnsHtml(Registry) {
  return (
    '<div class="site-footer__columns">' +
      FULL_COLUMNS.map((col) => {
        const links = col.links.map((l) => resolveLink(l, Registry));
        return (
          '<div>' +
            `<p class="site-footer__heading">${esc(col.heading)}</p>` +
            '<div class="site-footer__links">' +
              links.map((l) => `<a href="${esc(l.href)}">${esc(l.label)}</a>`).join('') +
            '</div>' +
          '</div>'
        );
      }).join('') +
    '</div>'
  );
}

function fullFooterHtml(Registry) {
  return (
    '<footer class="site-footer"><div class="container">' +
      '<div class="site-footer__top">' + brandBlockHtml() + columnsHtml(Registry) + '</div>' +
      bottomBarHtml(Registry) +
    '</div></footer>'
  );
}

// Finds the byte range of `<div class="site-footer__bottom">...</div>` by counting div-open/close
// tags from the match, not a lazy regex -- .site-footer__bottom-links nests its own <div>s, so a
// naive `[\s\S]*?</div>` would stop at the wrong closing tag.
function findBottomDivRange(html) {
  const openTag = '<div class="site-footer__bottom">';
  const start = html.indexOf(openTag);
  if (start === -1) return null;
  let depth = 1;
  let i = start + openTag.length;
  const tagRe = /<div[\s>]|<\/div>/g;
  tagRe.lastIndex = i;
  let m;
  while ((m = tagRe.exec(html))) {
    if (m[0] === '</div>') depth -= 1; else depth += 1;
    if (depth === 0) return { start, end: m.index + m[0].length };
  }
  return null;
}

function applyRegion(html, generated, variant) {
  const startIdx = html.indexOf(MARK_START);
  const endIdx = html.indexOf(MARK_END);
  if (startIdx !== -1 && endIdx !== -1 && endIdx > startIdx) {
    return html.slice(0, startIdx) + MARK_START + '\n' + generated + '\n' + MARK_END + html.slice(endIdx + MARK_END.length);
  }
  // No markers yet. Which existing structure to wrap depends on the variant -- trying the 'full'
  // whole-<footer> pattern for a 'bottom-only' page (or vice versa) would silently swallow real,
  // hand-curated content columns that must never be touched. This was a real bug caught during
  // this pass's own Group 2 dry run (screen/tv/ibis-ai/etc.'s Watch/Creators/Intelligence columns
  // got replaced instead of preserved) -- fixed here, not worked around.
  if (variant === 'full') {
    const footerStart = html.indexOf('<footer class="site-footer">');
    if (footerStart === -1) throw new Error('full variant: no <footer class="site-footer"> found to wrap.');
    let depth = 0, closeIdx = -1;
    const tagRe = /<footer\b[^>]*>|<\/footer>/g;
    tagRe.lastIndex = footerStart;
    let m;
    while ((m = tagRe.exec(html))) {
      if (m[0] === '</footer>') { depth -= 1; if (depth === 0) { closeIdx = m.index + m[0].length; break; } }
      else depth += 1;
    }
    if (closeIdx === -1) throw new Error('full variant: <footer class="site-footer"> never closed.');
    return html.slice(0, footerStart) + MARK_START + '\n' + generated + '\n' + MARK_END + html.slice(closeIdx);
  }
  // 'bottom-only': wrap ONLY the existing .site-footer__bottom div, depth-matched, leaving any
  // .site-footer__top / brand / content columns before it completely untouched.
  const range = findBottomDivRange(html);
  if (!range) throw new Error('bottom-only variant: no .site-footer__bottom div found to wrap.');
  return html.slice(0, range.start) + MARK_START + '\n' + generated + '\n' + MARK_END + html.slice(range.end);
}

function generatedFor(variant, Registry) {
  return variant === 'full' ? fullFooterHtml(Registry) : bottomBarHtml(Registry);
}

const Registry = loadRegistry();
const args = process.argv.slice(2);
const checkOnly = args.includes('--check');
const groupArg = args.find((a) => a.startsWith('--group='));
const onlyGroup = groupArg ? groupArg.split('=')[1] : null;

const targets = [];
for (const [variant, files] of Object.entries(PAGES)) {
  if (onlyGroup && onlyGroup !== variant) continue;
  for (const file of files) targets.push({ file, variant });
}

let changed = 0;
const drifted = [];
for (const { file, variant } of targets) {
  const path = resolve(root, file);
  const html = readFileSync(path, 'utf8');
  const generated = generatedFor(variant, Registry);
  const next = applyRegion(html, generated, variant);
  if (next === html) continue;
  changed += 1;
  if (checkOnly) {
    drifted.push(file);
  } else {
    writeFileSync(path, next);
  }
}

if (checkOnly) {
  if (drifted.length) {
    console.error(`${drifted.length}/${targets.length} footer(s) drifted from data/footer-config.mjs:`);
    console.error(drifted.map((f) => '  ' + f).join('\n'));
    console.error('Run: node scripts/sync-footer.mjs');
    process.exit(1);
  }
  console.log(`All ${targets.length} configured footers match data/footer-config.mjs.`);
} else {
  console.log(`Synced ${changed}/${targets.length} footer(s)${onlyGroup ? ` (group: ${onlyGroup})` : ''}.`);
}
