import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const MUSIC_EXCLUDED=/\b(?:dj\s*)?mix(?:es|tape)?\b|\bfull\s+mix\b|\bmega\s+mix\b|\bcontinuous\s+mix\b|\bmix\s*20\d\d\b|\bhour\s+mix\b|\bnonstop\b|\bnon-stop\b|\bcompilation\b|\bmedley\b|\bplaylist\b/i;
const ALLOWED_ORIGINS=new Set(["https://ftnplatform.org","https://www.ftnplatform.org","http://localhost:3000","http://127.0.0.1:3000"]);
const GENRE_SEEDS:Record<string,string[]>={
 soca:["soca Trinidad official video","soca Trinidad official audio","soca Caribbean artist official","soca 2026 official video","Trinidad soca artiste topic"],
 reggae:["reggae Caribbean official video","reggae Jamaica official audio","roots reggae Caribbean official","reggae artist official video","Jamaica reggae artiste topic"],
 dancehall:["dancehall Jamaica official video","dancehall Caribbean official audio","dancehall artist official video","dancehall 2026 official video","Jamaica dancehall artiste topic"],
 "zouk-kompa":["zouk official video Caribbean","kompa Haiti official video","zouk kompa official audio","French Caribbean music official video","Haiti kompa artiste topic"],
 chutney:["chutney soca Trinidad official video","chutney music Trinidad official audio","Indo Caribbean chutney official video","chutney soca artist official","Trinidad chutney artiste topic"],
 calypso:["calypso Trinidad official audio","calypso Trinidad official video","kaiso Trinidad official","calypso Caribbean artist official","Trinidad calypso artiste topic"],
 steelpan:["steelpan Trinidad official performance","steel orchestra Trinidad official","panorama Trinidad official","steelpan Caribbean official"],
 gospel:["Caribbean gospel official video","Trinidad gospel official audio","Jamaica gospel official video","Caribbean gospel artist official"]
};
function originAllowed(req:Request){const origin=req.headers.get("origin")||"",referer=req.headers.get("referer")||"";if(origin&&ALLOWED_ORIGINS.has(origin))return origin;for(const allowed of ALLOWED_ORIGINS)if(referer.startsWith(allowed+"/"))return allowed;return"";}
function validPublishableKey(req:Request){const supplied=req.headers.get("apikey")||"";if(!supplied)return false;try{const parsed=JSON.parse(Deno.env.get("SUPABASE_PUBLISHABLE_KEYS")||"{}");return Object.values(parsed).some(v=>v===supplied);}catch{return false;}}
function cors(origin:string){return{"access-control-allow-origin":origin||"https://ftnplatform.org","access-control-allow-methods":"POST,OPTIONS","access-control-allow-headers":"apikey,content-type,x-client-info","vary":"Origin","content-type":"application/json; charset=utf-8","cache-control":"public, max-age=120, stale-while-revalidate=300"};}
function json(req:Request,body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:cors(originAllowed(req))});}
function cleanText(v:unknown){return String(v||"").replace(/<[^>]*>/g,"").trim().slice(0,220);}
function musicAllowed(title:string){return!!title&&!MUSIC_EXCLUDED.test(title);}
function uniqueByVideoId(items:any[]){const seen=new Set<string>();return items.filter(x=>{const id=String(x.videoId||"");if(!id||seen.has(id))return false;seen.add(id);return true;});}
function isoDurationToSeconds(v:string){const m=String(v||"").match(/^PT(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?$/);if(!m)return null;return +(m[1]||0)*3600 + +(m[2]||0)*60 + +(m[3]||0);}
function clockToSeconds(v:string){const parts=String(v||"").trim().split(":").map(Number);if(!parts.length||parts.some(n=>!Number.isFinite(n)))return null;let s=0;for(const n of parts)s=s*60+n;return s;}
function textOf(x:any){if(!x)return"";if(typeof x.simpleText==="string")return cleanText(x.simpleText);if(Array.isArray(x.runs))return cleanText(x.runs.map((r:any)=>r.text||"").join(""));return"";}
function extractBalancedJson(html:string,start:number){let depth=0,inString=false,escape=false;for(let i=start;i<html.length;i++){const ch=html[i];if(inString){if(escape)escape=false;else if(ch==="\\")escape=true;else if(ch==='"')inString=false;continue;}if(ch==='"'){inString=true;continue;}if(ch==="{")depth++;else if(ch==="}"){depth--;if(depth===0)return html.slice(start,i+1);}}return"";}
function extractInitialData(html:string){const markers=["var ytInitialData = ","window['ytInitialData'] = ","window[\"ytInitialData\"] = "];for(const marker of markers){const at=html.indexOf(marker);if(at>=0){const start=html.indexOf("{",at+marker.length);if(start>=0){const raw=extractBalancedJson(html,start);if(raw)try{return JSON.parse(raw)}catch{}}}}const key='\"ytInitialData\":';const at=html.indexOf(key);if(at>=0){const start=html.indexOf("{",at+key.length);if(start>=0){const raw=extractBalancedJson(html,start);if(raw)try{return JSON.parse(raw)}catch{}}}return null;}
function collectVideoRenderers(node:any,out:any[]){if(!node||typeof node!=="object")return;if(node.videoRenderer)out.push(node.videoRenderer);if(Array.isArray(node)){for(const x of node)collectVideoRenderers(x,out);}else{for(const k of Object.keys(node))if(k!=="videoRenderer")collectVideoRenderers(node[k],out);}}
async function ytWebSearch(q:string,maxResults:number){
 const u=new URL("https://www.youtube.com/results");u.searchParams.set("search_query",q);u.searchParams.set("hl","en");u.searchParams.set("gl","TT");
 const r=await fetch(u,{headers:{"user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/151 Safari/537.36","accept-language":"en-US,en;q=0.9"}});if(!r.ok)throw new Error(`YouTube web search ${r.status}`);const html=await r.text(),data=extractInitialData(html);if(!data)throw new Error("YouTube web search format unavailable");const renderers:any[]=[];collectVideoRenderers(data,renderers);
 return uniqueByVideoId(renderers.map((v:any)=>{const thumbs=v.thumbnail?.thumbnails||[];return{videoId:v.videoId,title:textOf(v.title),channel:textOf(v.ownerText)||textOf(v.longBylineText)||textOf(v.shortBylineText),publishedAt:textOf(v.publishedTimeText)||null,thumbnail:thumbs.length?thumbs[thumbs.length-1].url:null,description:textOf(v.detailedMetadataSnippets?.[0]?.snippetText)||textOf(v.descriptionSnippet),durationSeconds:clockToSeconds(textOf(v.lengthText)),liveBroadcastContent:v.badges?.some((b:any)=>/live/i.test(textOf(b.metadataBadgeRenderer?.label||b.metadataBadgeRenderer)))?"live":"none",source:"youtube-web",watchUrl:`https://www.youtube.com/watch?v=${v.videoId}`,embeddable:null};})).filter(x=>x.videoId&&x.title).slice(0,maxResults);
}
async function ytSearchApi(key:string,q:string,maxResults:number,videoCategoryId?:string){const u=new URL("https://www.googleapis.com/youtube/v3/search");u.searchParams.set("part","snippet");u.searchParams.set("type","video");u.searchParams.set("maxResults",String(Math.min(50,Math.max(1,maxResults))));u.searchParams.set("q",q);u.searchParams.set("safeSearch","moderate");u.searchParams.set("videoEmbeddable","true");u.searchParams.set("videoSyndicated","true");u.searchParams.set("order","relevance");u.searchParams.set("key",key);if(videoCategoryId)u.searchParams.set("videoCategoryId",videoCategoryId);const r=await fetch(u);if(!r.ok){const body=await r.text();throw new Error(`YouTube API search ${r.status}: ${body.slice(0,160)}`);}const d=await r.json();return(d.items||[]).map((x:any)=>({videoId:x.id?.videoId,title:cleanText(x.snippet?.title),channel:cleanText(x.snippet?.channelTitle),publishedAt:x.snippet?.publishedAt||null,thumbnail:x.snippet?.thumbnails?.high?.url||x.snippet?.thumbnails?.medium?.url||null,description:cleanText(x.snippet?.description),source:"youtube-api"}));}
async function enrichApi(key:string,items:any[],mode:string){const ids=uniqueByVideoId(items).map(x=>x.videoId).filter(Boolean);if(!ids.length)return[];const meta=new Map<string,any>();for(let i=0;i<ids.length;i+=50){const u=new URL("https://www.googleapis.com/youtube/v3/videos");u.searchParams.set("part","status,contentDetails,snippet,liveStreamingDetails");u.searchParams.set("id",ids.slice(i,i+50).join(","));u.searchParams.set("key",key);const r=await fetch(u);if(!r.ok)throw new Error(`YouTube videos ${r.status}`);const d=await r.json();for(const x of d.items||[])meta.set(x.id,x);}return uniqueByVideoId(items).filter(x=>{const m=meta.get(x.videoId);if(!m||m.status?.privacyStatus!=="public"||m.status?.embeddable===false)return false;if(mode==="music"&&!musicAllowed(x.title))return false;const secs=isoDurationToSeconds(m?.contentDetails?.duration);if(mode==="music"&&secs&&secs>15*60)return false;return true;}).map(x=>{const m=meta.get(x.videoId);return{...x,durationSeconds:isoDurationToSeconds(m?.contentDetails?.duration),definition:m?.contentDetails?.definition||null,liveBroadcastContent:m?.snippet?.liveBroadcastContent||"none",licensedContent:!!m?.contentDetails?.licensedContent,embeddable:true,watchUrl:`https://www.youtube.com/watch?v=${x.videoId}`};});}
function filterWeb(items:any[],mode:string){return uniqueByVideoId(items).filter(x=>{if(mode==="music"&&!musicAllowed(x.title))return false;if(mode==="music"&&x.durationSeconds&&x.durationSeconds>15*60)return false;return true;});}
async function discovery(body:any){const key=Deno.env.get("YOUTUBE_DATA_API_KEY")||"";const mode=String(body.mode||body.contentType||"music").toLowerCase(),genre=String(body.genre||"").toLowerCase().trim(),limit=Math.min(160,Math.max(1,Number(body.limit)||100));let queries:string[]=[];if(Array.isArray(body.queries))queries=body.queries.map(cleanText).filter(Boolean).slice(0,6);if(!queries.length&&genre&&GENRE_SEEDS[genre])queries=GENRE_SEEDS[genre];if(!queries.length&&cleanText(body.query))queries=[cleanText(body.query)];if(!queries.length)throw new Error("query, queries, or supported genre required");const perQuery=Math.min(50,Math.max(15,Math.ceil(limit/queries.length)+5));let provider="youtube-web",warning:string|null=null,results:any[]=[];
 if(key){try{const batches=await Promise.all(queries.map(q=>ytSearchApi(key,q,perQuery,mode==="music"?"10":undefined)));results=await enrichApi(key,batches.flat(),mode);provider="youtube-data-api";}catch(e){warning=e instanceof Error?e.message:String(e);}}
 if(!results.length){const batches=await Promise.all(queries.map(q=>ytWebSearch(q,perQuery).catch(()=>[])));results=filterWeb(batches.flat(),mode);provider="youtube-public-search";}
 return{query:cleanText(body.query),queries,genre:genre||null,mode,results:results.slice(0,limit),providers:{youtube:true,provider,apiConfigured:!!key},warning,excludedMixes:mode==="music",fallbackUsed:provider!=="youtube-data-api"};}
async function playlist(body:any){const key=Deno.env.get("YOUTUBE_DATA_API_KEY")||"";const playlistId=cleanText(body.playlistId);if(!playlistId)throw new Error("playlistId required");if(!key)throw new Error("Playlist import requires the YouTube Data API key; generic discovery remains available through the public-search fallback.");const mode=String(body.mode||"music").toLowerCase(),limit=Math.min(250,Math.max(1,Number(body.limit)||160)),out:any[]=[];let page="";do{const u=new URL("https://www.googleapis.com/youtube/v3/playlistItems");u.searchParams.set("part","snippet,contentDetails");u.searchParams.set("playlistId",playlistId);u.searchParams.set("maxResults","50");u.searchParams.set("key",key);if(page)u.searchParams.set("pageToken",page);const r=await fetch(u);if(!r.ok)throw new Error(`YouTube playlist ${r.status}`);const d=await r.json();for(const x of d.items||[]){const title=cleanText(x.snippet?.title);if(mode!=="music"||musicAllowed(title))out.push({title,videoId:x.contentDetails?.videoId,channel:cleanText(x.snippet?.videoOwnerChannelTitle||x.snippet?.channelTitle),thumbnail:x.snippet?.thumbnails?.high?.url||null,source:"youtube-playlist"});}page=d.nextPageToken||"";}while(page&&out.length<limit);const results=await enrichApi(key,out,mode);return{playlistId,mode,results:results.slice(0,limit),providers:{youtube:true,provider:"youtube-data-api"},excludedMixes:mode==="music"};}
Deno.serve(async req=>{const origin=originAllowed(req);if(req.method==="OPTIONS")return new Response(null,{status:origin?204:403,headers:cors(origin)});if(req.method!=="POST")return json(req,{error:"POST required"},405);if(!origin)return json(req,{error:"Origin not allowed"},403);if(!validPublishableKey(req))return json(req,{error:"Invalid FTN client key"},401);try{const body=await req.json(),result=body.playlistId?await playlist(body):await discovery(body);return json(req,result);}catch(e){return json(req,{error:e instanceof Error?e.message:String(e)},400);}});
