import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const ALLOWED=new Set(["https://ftnplatform.org","https://www.ftnplatform.org","http://localhost:3000","http://127.0.0.1:3000"]);const URL="https://caricom.org/category/pressreleases/";
function origin(req:Request){const o=req.headers.get("origin")||"",r=req.headers.get("referer")||"";if(o&&ALLOWED.has(o))return o;for(const a of ALLOWED)if(r.startsWith(a+"/"))return a;return"";}
function key(req:Request){const k=req.headers.get("apikey")||"";try{return!!k&&Object.values(JSON.parse(Deno.env.get("SUPABASE_PUBLISHABLE_KEYS")||"{}")).includes(k)}catch{return false}}
function h(o:string){return{"content-type":"application/json; charset=utf-8","access-control-allow-origin":o||"https://ftnplatform.org","access-control-allow-methods":"GET,OPTIONS","access-control-allow-headers":"apikey,content-type","vary":"Origin","cache-control":"public, max-age=600, stale-while-revalidate=1200"}}
function j(req:Request,b:unknown,s=200){return new Response(JSON.stringify(b),{status:s,headers:h(origin(req))})}
function clean(v:string){return v.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&amp;/g,'&').replace(/&#8217;|&rsquo;/g,'’').replace(/&#8211;|&ndash;/g,'–').replace(/&quot;/g,'"').replace(/&#038;/g,'&').replace(/&nbsp;/g,' ').replace(/\s+/g,' ').trim()}
function validStoryTitle(t:string){if(t.length<18||t.length>220)return false;return !/^(read more|home|about|news|press releases?|media release|contact|search|previous|next|older|newer|caricom|secretariat)$/i.test(t)&&!/cookie|privacy|facebook|twitter|instagram|youtube|linkedin|skip to/i.test(t)}
function dateNear(html:string,index:number){const from=Math.max(0,index-900),to=Math.min(html.length,index+1100),near=clean(html.slice(from,to));return(near.match(/(?:January|February|March|April|May|June|July|August|September|October|November|December)\s+\d{1,2},\s+\d{4}/i)||[])[0]||null}
function excerptNear(html:string,index:number,title:string){const from=Math.max(0,index-250),to=Math.min(html.length,index+1800),near=clean(html.slice(from,to)).replace(title,'').trim();return near.slice(0,420)}
function parse(html:string){const out:any[]=[],seen=new Set<string>();const re=/<a\s+[^>]*href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi;let m;while((m=re.exec(html))){let href=m[1];if(!href||href.startsWith('#')||href.startsWith('mailto:')||href.startsWith('javascript:'))continue;let url:string;try{url=new URL(href,URL).href}catch{continue}if(!/^https?:\/\/(?:www\.)?caricom\.org\//i.test(url))continue;if(/\/category\/|\/tag\/|\/author\/|\/page\/\d+\/?$|\/wp-content\/|\/feed\/?$|\/search\//i.test(url))continue;const title=clean(m[2]);if(!validStoryTitle(title)||seen.has(url))continue;seen.add(url);const publishedAt=dateNear(html,m.index||0),excerpt=excerptNear(html,m.index||0,title);out.push({title,url,publisher:"CARICOM",publishedAt,excerpt,classification:"Official institutional release",verificationState:"Source identified; editorial verification still required"});if(out.length>=30)break;}return out}
Deno.serve(async req=>{const o=origin(req);if(req.method==="OPTIONS")return new Response(null,{status:o?204:403,headers:h(o)});if(req.method!=="GET")return j(req,{error:"GET required"},405);if(!o)return j(req,{error:"Origin not allowed"},403);if(!key(req))return j(req,{error:"Invalid FTN client key"},401);try{const r=await fetch(URL,{headers:{"user-agent":"Mozilla/5.0 FTN-Kaiso/1.0 (+https://ftnplatform.org/kaiso/)","accept-language":"en-US,en;q=0.9"}});if(!r.ok)throw new Error(`CARICOM ${r.status}`);const html=await r.text(),items=parse(html);return j(req,{items,source:{name:"CARICOM Press Releases",url:URL},fetchedAt:new Date().toISOString(),notice:"Source radar metadata is for newsroom discovery. Publication by FTN requires independent editorial verification and source review.",parserState:items.length?"ok":"source-returned-no-items"});}catch(e){return j(req,{error:e instanceof Error?e.message:String(e),source:{name:"CARICOM Press Releases",url:URL}},502)}});
